package id.go.ojk.conf.client.field.reference;

import java.util.ArrayList;
import java.util.List;

import id.go.ojk.lib.client.IObject;
import id.go.ojk.lib.client.model.KeyValueString;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum ER1037Negara implements IObject<KeyValueString> {
	R_AF ("AF", "AFGHANISTAN"),
	R_AL ("AL", "ALBANIA"),
	R_DZ ("DZ", "ALGERIA/ ALJAZAIR"),
	R_AS ("AS", "AMERICA SAMOA"),
	R_AD ("AD", "ANDORRA"),
	R_AO ("AO", "ANGOLA"),
	R_AI ("AI", "ANGUILLA"),
	R_AQ ("AQ", "ANTARCTICA"),
	R_AG ("AG", "ANTIGUA AND BARBUDA"),
	R_AR ("AR", "ARGENTINA"),
	R_AM ("AM", "ARMENIA"),
	R_AW ("AW", "ARUBA"),
	R_AU ("AU", "AUSTRALIA"),
	R_AT ("AT", "AUSTRIA"),
	R_AZ ("AZ", "AZERBAIJAN"),
	R_BS ("BS", "BAHAMAS"),
	R_BH ("BH", "BAHRAIN"),
	R_BD ("BD", "BANGLADESH"),
	R_BB ("BB", "BARBADOS"),
	R_BY ("BY", "BELARUS"),
	R_BE ("BE", "BELGIUM"),
	R_BZ ("BZ", "BELIZE"),
	R_BJ ("BJ", "BENIN"),
	R_BM ("BM", "BERMUDA"),
	R_BT ("BT", "BHUTAN"),
	R_BO ("BO", "BOLIVIA"),
	R_BA ("BA", "BOSNIA-HERZEGOWINA"),
	R_BW ("BW", "BOTSWANA"),
	R_BV ("BV", "BOUVET ISLAND"),
	R_BR ("BR", "BRAZIL"),
	R_IO ("IO", "BRITISH INDIAN OCEAN TERRITORY"),
	R_BN ("BN", "BRUNEI DARUSSALAM"),
	R_BG ("BG", "BULGARIA"),
	R_BF ("BF", "BURKINA FASO"),
	R_BI ("BI", "BURUNDI"),
	R_KH ("KH", "CAMBODIA"),
	R_CM ("CM", "CAMEROON"),
	R_CA ("CA", "CANADA"),
	R_CV ("CV", "CAPE VERDE"),
	R_KY ("KY", "CAYMAN ISLANDS"),
	R_CF ("CF", "CENTRAL AFRICAN REPUBLIC"),
	R_TD ("TD", "CHAD"),
	R_CL ("CL", "CHILE"),
	R_CN ("CN", "CHINA"),
	R_CX ("CX", "CHRISTMAS ISLANDS"),
	R_CC ("CC", "COCOS (KEELING) ISLAND"),
	R_CO ("CO", "COLOMBIA"),
	R_KM ("KM", "COMOROS"),
	R_CG ("CG", "CONGO"),
	R_CD ("CD", "CONGO, THE DEMOCRATIC REPUBLIC OF THE"),
	R_CK ("CK", "COOK ISLAND"),
	R_CR ("CR", "COSTA RICA"),
	R_HR ("HR", "CROATIA"),
	R_CU ("CU", "CUBA"),
	R_CY ("CY", "CYPRUS"),
	R_CZ ("CZ", "CZECH REPUBLIC"),
	R_DK ("DK", "DENMARK"),
	R_DJ ("DJ", "DJIBOUTI"),
	R_DO ("DO", "DOMINICAN REPUBLIC"),
	R_DM ("DM", "DOMINICA"),
	R_EC ("EC", "ECUADOR"),
	R_EG ("EG", "EGYPT"),
	R_SV ("SV", "EL SALVADOR"),
	R_GQ ("GQ", "EQUATORIAL GUINEA"),
	R_ER ("ER", "ERITREA"),
	R_EE ("EE", "ESTONIA"),
	R_ET ("ET", "ETHIOPIA"),
	R_FK ("FK", "FALKLAND ISLANDS"),
	R_FO ("FO", "FAROE ISLANDS"),
	R_FJ ("FJ", "FIJI"),
	R_FI ("FI", "FINLAND"),
	R_FR ("FR", "FRANCE"),
	R_FX ("FX", "FRANCE, METROPOLITAN"),
	R_GF ("GF", "FRENCH GUIANA"),
	R_PF ("PF", "FRENCH POLYNESIA"),
	R_TF ("TF", "FRENCH SOUTHERN TERRITORIES"),
	R_GA ("GA", "GABON"),
	R_GM ("GM", "GAMBIA"),
	R_GE ("GE", "GEORGIA"),
	R_DE ("DE", "GERMANY"),
	R_GH ("GH", "GHANA"),
	R_GI ("GI", "GIBRALTAR"),
	R_GL ("GL", "GREENLAND"),
	R_GD ("GD", "GRENADA"),
	R_GP ("GP", "GUADELOUPE"),
	R_GU ("GU", "GUAM"),
	R_GT ("GT", "GUATEMALA"),
	R_GN ("GN", "GUINEA"),
	R_GW ("GW", "GUINEA BISSAU"),
	R_GY ("GY", "GUYANA"),
	R_HT ("HT", "HAITI"),
	R_HM ("HM", "HEARD AND MCDONALD ISLAND"),
	R_HN ("HN", "HONDURAS"),
	R_HK ("HK", "HONGKONG"),
	R_HU ("HU", "HUNGARY"),
	R_IS ("IS", "ICELAND"),
	R_IN ("IN", "INDIA"),
	R_ID ("ID", "INDONESIA"),
	R_IR ("IR", "IRAN"),
	R_IQ ("IQ", "IRAQ"),
	R_IE ("IE", "IRELAND"),
	R_IL ("IL", "ISRAEL"),
	R_IT ("IT", "ITALIA"),
	R_CI ("CI", "IVORY COAST"),
	R_JM ("JM", "JAMAICA"),
	R_JP ("JP", "JAPAN"),
	R_JO ("JO", "JORDAN"),
	R_KZ ("KZ", "KAZAKHSTAN"),
	R_KE ("KE", "KENYA"),
	R_KI ("KI", "KIRIBATI"),
	R_KR ("KR", "KOREA SELATAN"),
	R_KP ("KP", "KOREA UTARA"),
	R_KW ("KW", "KUWAIT"),
	R_KG ("KG", "KYRGYZSTAN"),
	R_LA ("LA", "LAO PEOPLE S DEMOC. REP."),
	R_LV ("LV", "LATVIA"),
	R_LB ("LB", "LEBANON"),
	R_LS ("LS", "LESOTHO"),
	R_LR ("LR", "LIBERIA"),
	R_LY ("LY", "LIBYAN ARAB JAMAHIRIYA"),
	R_LI ("LI", "LIECHTENSTEIN"),
	R_LT ("LT", "LITHUANIA"),
	R_LU ("LU", "LUXEMBOURG"),
	R_MO ("MO", "MACAU"),
	R_MK ("MK", "MACEDONIA"),
	R_MG ("MG", "MADAGASCAR"),
	R_MW ("MW", "MALAWI"),
	R_MY ("MY", "MALAYSIA"),
	R_MV ("MV", "MALDIVES"),
	R_ML ("ML", "MALI"),
	R_MT ("MT", "MALTA"),
	R_MH ("MH", "MARSHALL ISLANDS"),
	R_MQ ("MQ", "MARTINIQUE"),
	R_MR ("MR", "MAURITANIA"),
	R_MU ("MU", "MAURITIUS"),
	R_YT ("YT", "MAYOTTE"),
	R_MX ("MX", "MEXICO"),
	R_FM ("FM", "MICRONESIA, FEDERATED STATE OF"),
	R_MD ("MD", "MOLDOVA, REPUBLIC OF"),
	R_MC ("MC", "MONACO"),
	R_MN ("MN", "MONGOLIA"),
	R_MS ("MS", "MONTSERRAT"),
	R_MA ("MA", "MOROCCO"),
	R_MZ ("MZ", "MOZAMBIQUE"),
	R_MM ("MM", "MYANMAR (BURMA)"),
	R_NA ("NA", "NAMIBIA"),
	R_NR ("NR", "NAURU"),
	R_NP ("NP", "NEPAL"),
	R_NL ("NL", "NETHERLANDS"),
	R_AN ("AN", "NETHERLANDS ANTILLES"),
	R_NC ("NC", "NEW CALEDONIA"),
	R_NZ ("NZ", "NEW ZEALAND"),
	R_NI ("NI", "NICARAGUA"),
	R_NU ("NU", "NIEUE"),
	R_NE ("NE", "NIGER"),
	R_NG ("NG", "NIGERIA"),
	R_NF ("NF", "NORFOLK ISLANDS"),
	R_MP ("MP", "NORTHERN MARIANA ISLAND"),
	R_NO ("NO", "NORWAY"),
	R_OM ("OM", "OMAN"),
	R_PK ("PK", "PAKISTAN"),
	R_PW ("PW", "PALAU"),
	R_PA ("PA", "PANAMA"),
	R_PG ("PG", "PAPUA NEW GUINEA"),
	R_PY ("PY", "PARAGUAY"),
	R_PE ("PE", "PERU"),
	R_PH ("PH", "PHILIPPINES"),
	R_PN ("PN", "PITCAIRN"),
	R_PL ("PL", "POLAND"),
	R_PT ("PT", "PORTUGAL"),
	R_PR ("PR", "PUERTO RICO"),
	R_QA ("QA", "QATAR"),
	R_RE ("RE", "REUNION"),
	R_RO ("RO", "ROMANIA"),
	R_RU ("RU", "RUSSIAN FEDERATION"),
	R_RW ("RW", "RWANDA"),
	R_LC ("LC", "SAINT LUCIA"),
	R_WS ("WS", "SAMOA"),
	R_SM ("SM", "SAN MARINO"),
	R_ST ("ST", "SAO TOME & PRINCIPE"),
	R_SA ("SA", "SAUDI ARABIA"),
	R_SN ("SN", "SENEGAL"),
	R_SC ("SC", "SEYCHELLES"),
	R_SL ("SL", "SIERA LEONER"),
	R_SG ("SG", "SINGAPORE"),
	R_SK ("SK", "SLOVAKIA (SLOVAK REPUBLIC)"),
	R_SI ("SI", "SLOVENIA"),
	R_SB ("SB", "SOLOMON ISLANDS"),
	R_SO ("SO", "SOMALIA"),
	R_ZA ("ZA", "SOUTH AFRICA"),
	R_GS ("GS", "SOUTH GEORGIA AND THE SOUTH SANDWICH  I."),
	R_ES ("ES", "SPAIN"),
	R_LK ("LK", "SRI LANGKA/CEYLON"),
	R_SH ("SH", "ST. HELENA"),
	R_KN ("KN", "ST. KITTAND NEVIS/ SAINT KITTS C. AND NEVIS"),
	R_PM ("PM", "ST. PIERRE & MIQUELON"),
	R_VC ("VC", "ST. VINCENT & THE GRENADES"),
	R_SD ("SD", "SUDAN"),
	R_SR ("SR", "SURINAME"),
	R_SJ ("SJ", "SVALBARD AND JAN MAYEN ISLAND"),
	R_SZ ("SZ", "SWAZILAND"),
	R_SE ("SE", "SWEDIA/SWEDEN"),
	R_CH ("CH", "SWISS/SWITZERLAND"),
	R_SY ("SY", "SYRIAN ARAB REPUBLIC"),
	R_TW ("TW", "TAIWAN/REP. OF CHINA/PROVINCE OF CHINA"),
	R_TJ ("TJ", "TAJIKISTAN"),
	R_TZ ("TZ", "TANZANIA (TAGANZICA & ZANZIBAR)"),
	R_TH ("TH", "THAILAND"),
	R_TG ("TG", "TOGO"),
	R_TK ("TK", "TOKELAU"),
	R_TO ("TO", "TONGA"),
	R_TT ("TT", "TRINIDAD & TOBAGO"),
	R_TN ("TN", "TUNISIA"),
	R_TR ("TR", "TURKEY"),
	R_TM ("TM", "TURKMENISTAN"),
	R_TC ("TC", "TURKS & CAICOS ISLAND"),
	R_TV ("TV", "TUVALU"),
	R_UG ("UG", "UGANDA"),
	R_UA ("UA", "UKRAINE"),
	R_SU ("SU", "UNION OF SOVIET SOCIALIST REPUBLICS"),
	R_AE ("AE", "UNITED ARAB EMIRAT"),
	R_GB ("GB", "UNITED KINGDOM (INGGRIS)"),
	R_US ("US", "UNITED STATES OF AMERICA"),
	R_UY ("UY", "URUGUAY"),
	R_UM ("UM", "US MINOR OUTLYING ISLANDS"),
	R_UZ ("UZ", "UZBEKISTAN"),
	R_VU ("VU", "VANUATU"),
	R_VA ("VA", "VATICAN CITY STATE (HOLY SEE)"),
	R_VE ("VE", "VENEZUELA"),
	R_VN ("VN", "VIETNAM"),
	R_VG ("VG", "VIRGIN ISLANDS (BRITISH)"),
	R_VI ("VI", "VIRGIN ISLANDS (US)"),
	R_WF ("WF", "WALLIS AND FUTUNA ISLANDS"),
	R_XO ("XO", "WEST AFRICA"),
	R_EH ("EH", "WESTERN SAHARA"),
	R_YE ("YE", "YEMEN"),
	R_YU ("YU", "YUGOSLAVIA"),
	R_GR ("GR", "YUNANI (lihat Greece)"),
	R_ZM ("ZM", "ZAMBIA"),
	R_ZW ("ZW", "ZIMBABWE"),
	R_N1 ("N1", "LAINNYA"),
	R_TL ("TL", "Timor Leste"),
	;

	private String key;
	private String value;
	
	public KeyValueString getObject() {
		return new KeyValueString(key, value, new String[] {});
	}

	public static List<KeyValueString> getObjects() {
		List<KeyValueString> res = new ArrayList<>();
		for (ER1037Negara eEnum : ER1037Negara.values()) {
			res.add(eEnum.getObject());
		}
		return res;
	}
	
	public static String getName() {
		return ER1037Negara.class.getSimpleName().substring(6);
	}
	
	public static int getRefNumber() {
		return Integer.parseInt(ER1037Negara.class.getSimpleName().substring(2, 6));
	}
}
