package id.go.ojk.conf.client.field.reference;

import java.util.ArrayList;
import java.util.List;

import id.go.ojk.conf.client.UtilMetadata;
import id.go.ojk.lib.client.IObject;
import id.go.ojk.lib.client.model.KeyValueString;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum ER1126Negara implements IObject<KeyValueString> {
	R_1 ("LO:ID", "Indonesia"),
	R_2 ("LO:AD", "Andorra"),
	R_3 ("LO:AE", "United Arab Emirates"),
	R_4 ("LO:AF", "Afghanistan"),
	R_5 ("LO:AG", "Antigua and Barbuda"),
	R_6 ("LO:AI", "Anguilla"),
	R_7 ("LO:AL", "Albania"),
	R_8 ("LO:AM", "Armenia"),
	R_9 ("LO:AO", "Angola"),
	R_10 ("LO:AQ", "Antarctica"),
	R_11 ("LO:AR", "Argentina"),
	R_12 ("LO:AS", "American Samoa"),
	R_13 ("LO:AT", "Austria"),
	R_14 ("LO:AU", "Australia"),
	R_15 ("LO:AW", "Aruba"),
	R_16 ("LO:AX", "Åland"),
	R_17 ("LO:AZ", "Azerbaijan"),
	R_18 ("LO:BA", "Bosnia and Herzegovina"),
	R_19 ("LO:BB", "Barbados"),
	R_20 ("LO:BD", "Bangladesh"),
	R_21 ("LO:BE", "Belgium"),
	R_22 ("LO:BF", "Burkina Faso"),
	R_23 ("LO:BG", "Bulgaria"),
	R_24 ("LO:BH", "Bahrain"),
	R_25 ("LO:BI", "Burundi"),
	R_26 ("LO:BJ", "Benin"),
	R_27 ("LO:BL", "Saint Barthélemy"),
	R_28 ("LO:BM", "Bermuda"),
	R_29 ("LO:BN", "Brunei Darussalam"),
	R_30 ("LO:BO", "Bolivia"),
	R_31 ("LO:BQ", "Bonaire, Sint Eustatius and Saba"),
	R_32 ("LO:BR", "Brazil"),
	R_33 ("LO:BS", "Bahamas"),
	R_34 ("LO:BT", "Bhutan"),
	R_35 ("LO:BV", "Bouvet Island"),
	R_36 ("LO:BW", "Botswana"),
	R_37 ("LO:BY", "Belarus"),
	R_38 ("LO:BZ", "Belize"),
	R_39 ("LO:CA", "Canada"),
	R_40 ("LO:CC", "Cocos (Keeling) Islands"),
	R_41 ("LO:CD", "Congo (Kinshasa)"),
	R_42 ("LO:CF", "Central African Republic"),
	R_43 ("LO:CG", "Congo (Brazzaville)"),
	R_44 ("LO:CH", "Switzerland"),
	R_45 ("LO:CI", "Cote d'Ivoire"),
	R_46 ("LO:CK", "Cook Islands"),
	R_47 ("LO:CL", "Chile"),
	R_48 ("LO:CM", "Cameroon"),
	R_49 ("LO:CN", "China"),
	R_50 ("LO:CO", "Colombia"),
	R_51 ("LO:CR", "Costa Rica"),
	R_52 ("LO:CU", "Cuba"),
	R_53 ("LO:CV", "Cape Verde"),
	R_54 ("LO:CW", "Curaçao"),
	R_55 ("LO:CX", "Christmas Island"),
	R_56 ("LO:CY", "Cyprus"),
	R_57 ("LO:CZ", "Czech Republic"),
	R_58 ("LO:DE", "Germany"),
	R_59 ("LO:DJ", "Djibouti"),
	R_60 ("LO:DK", "Denmark"),
	R_61 ("LO:DM", "Dominica"),
	R_62 ("LO:DO", "Dominican Republic"),
	R_63 ("LO:DZ", "Algeria"),
	R_64 ("LO:EC", "Ecuador"),
	R_65 ("LO:EE", "Estonia"),
	R_66 ("LO:EG", "Egypt"),
	R_67 ("LO:EH", "Western Sahara"),
	R_68 ("LO:ER", "Eritrea"),
	R_69 ("LO:ES", "Spain"),
	R_70 ("LO:ET", "Ethiopia"),
	R_71 ("LO:FI", "Finland"),
	R_72 ("LO:FJ", "Fiji"),
	R_73 ("LO:FK", "Falkland Islands"),
	R_74 ("LO:FM", "Micronesia"),
	R_75 ("LO:FO", "Faroe Islands"),
	R_76 ("LO:FR", "France"),
	R_77 ("LO:GA", "Gabon"),
	R_78 ("LO:GB", "United Kingdom"),
	R_79 ("LO:GD", "Grenada"),
	R_80 ("LO:GE", "Georgia"),
	R_81 ("LO:GF", "French Guiana"),
	R_82 ("LO:GG", "Guernsey"),
	R_83 ("LO:GH", "Ghana"),
	R_84 ("LO:GI", "Gibraltar"),
	R_85 ("LO:GL", "Greenland"),
	R_86 ("LO:GM", "Gambia"),
	R_87 ("LO:GN", "Guinea"),
	R_88 ("LO:GP", "Guadeloupe"),
	R_89 ("LO:GQ", "Equatorial Guinea"),
	R_90 ("LO:GR", "Greece"),
	R_91 ("LO:GS", "South Georgia and South Sandwich Islands"),
	R_92 ("LO:GT", "Guatemala"),
	R_93 ("LO:GU", "Guam"),
	R_94 ("LO:GW", "Guinea-Bissau"),
	R_95 ("LO:GY", "Guyana"),
	R_96 ("LO:HK", "Hong Kong"),
	R_97 ("LO:HM", "Heard and McDonald Islands"),
	R_98 ("LO:HN", "Honduras"),
	R_99 ("LO:HR", "Croatia"),
	R_100 ("LO:HT", "Haiti"),
	R_101 ("LO:HU", "Hungary"),
	R_102 ("LO:IE", "Ireland"),
	R_103 ("LO:IL", "Israel"),
	R_104 ("LO:IM", "Isle of Man"),
	R_105 ("LO:IN", "India"),
	R_106 ("LO:IO", "British Indian Ocean Territory"),
	R_107 ("LO:IQ", "Iraq"),
	R_108 ("LO:IR", "Iran"),
	R_109 ("LO:IS", "Iceland"),
	R_110 ("LO:IT", "Italy"),
	R_111 ("LO:JE", "Jersey"),
	R_112 ("LO:JM", "Jamaica"),
	R_113 ("LO:JO", "Jordan"),
	R_114 ("LO:JP", "Japan"),
	R_115 ("LO:KE", "Kenya"),
	R_116 ("LO:KG", "Kyrgyzstan"),
	R_117 ("LO:KH", "Cambodia"),
	R_118 ("LO:KI", "Kiribati"),
	R_119 ("LO:KM", "Comoros"),
	R_120 ("LO:KN", "Saint Kitts and Nevis"),
	R_121 ("LO:KP", "Korea, North"),
	R_122 ("LO:KR", "Korea, South"),
	R_123 ("LO:KW", "Kuwait"),
	R_124 ("LO:KY", "Cayman Islands"),
	R_125 ("LO:KZ", "Kazakhstan"),
	R_126 ("LO:LA", "Laos"),
	R_127 ("LO:LB", "Lebanon"),
	R_128 ("LO:LC", "Saint Lucia"),
	R_129 ("LO:LI", "Liechtenstein"),
	R_130 ("LO:LK", "Sri Lanka"),
	R_131 ("LO:LR", "Liberia"),
	R_132 ("LO:LS", "Lesotho"),
	R_133 ("LO:LT", "Lithuania"),
	R_134 ("LO:LU", "Luxembourg"),
	R_135 ("LO:LV", "Latvia"),
	R_136 ("LO:LY", "Libya"),
	R_137 ("LO:MA", "Morocco"),
	R_138 ("LO:MC", "Monaco"),
	R_139 ("LO:MD", "Moldova"),
	R_140 ("LO:ME", "Montenegro"),
	R_141 ("LO:MF", "Saint Martin (French part)"),
	R_142 ("LO:MG", "Madagascar"),
	R_143 ("LO:MH", "Marshall Islands"),
	R_144 ("LO:MK", "Macedonia"),
	R_145 ("LO:ML", "Mali"),
	R_146 ("LO:MM", "Myanmar"),
	R_147 ("LO:MN", "Mongolia"),
	R_148 ("LO:MO", "Macau"),
	R_149 ("LO:MP", "Northern Mariana Islands"),
	R_150 ("LO:MQ", "Martinique"),
	R_151 ("LO:MR", "Mauritania"),
	R_152 ("LO:MS", "Montserrat"),
	R_153 ("LO:MT", "Malta"),
	R_154 ("LO:MU", "Mauritius"),
	R_155 ("LO:MV", "Maldives"),
	R_156 ("LO:MW", "Malawi"),
	R_157 ("LO:MX", "Mexico"),
	R_158 ("LO:MY", "Malaysia"),
	R_159 ("LO:MZ", "Mozambique"),
	R_160 ("LO:NA", "Namibia"),
	R_161 ("LO:NC", "New Caledonia"),
	R_162 ("LO:NE", "Niger"),
	R_163 ("LO:NF", "Norfolk Island"),
	R_164 ("LO:NG", "Nigeria"),
	R_165 ("LO:NI", "Nicaragua"),
	R_166 ("LO:NL", "Netherlands"),
	R_167 ("LO:NO", "Norway"),
	R_168 ("LO:NP", "Nepal"),
	R_169 ("LO:NR", "Nauru"),
	R_170 ("LO:NU", "Niue"),
	R_171 ("LO:NZ", "New Zealand"),
	R_172 ("LO:OM", "Oman"),
	R_173 ("LO:PA", "Panama"),
	R_174 ("LO:PE", "Peru"),
	R_175 ("LO:PF", "French Polynesia"),
	R_176 ("LO:PG", "Papua New Guinea"),
	R_177 ("LO:PH", "Philippines"),
	R_178 ("LO:PK", "Pakistan"),
	R_179 ("LO:PL", "Poland"),
	R_180 ("LO:PM", "Saint Pierre and Miquelon"),
	R_181 ("LO:PN", "Pitcairn"),
	R_182 ("LO:PR", "Puerto Rico"),
	R_183 ("LO:PS", "Palestine"),
	R_184 ("LO:PT", "Portugal"),
	R_185 ("LO:PW", "Palau"),
	R_186 ("LO:PY", "Paraguay"),
	R_187 ("LO:QA", "Qatar"),
	R_188 ("LO:RE", "Reunion"),
	R_189 ("LO:RO", "Romania"),
	R_190 ("LO:RS", "Serbia"),
	R_191 ("LO:RU", "Russian Federation"),
	R_192 ("LO:RW", "Rwanda"),
	R_193 ("LO:SA", "Saudi Arabia"),
	R_194 ("LO:SB", "Solomon Islands"),
	R_195 ("LO:SC", "Seychelles"),
	R_196 ("LO:SD", "Sudan"),
	R_197 ("LO:SE", "Sweden"),
	R_198 ("LO:SG", "Singapore"),
	R_199 ("LO:SH", "Saint Helena"),
	R_200 ("LO:SI", "Slovenia"),
	R_201 ("LO:SJ", "Svalbard and Jan Mayen Islands"),
	R_202 ("LO:SK", "Slovakia"),
	R_203 ("LO:SL", "Sierra Leone"),
	R_204 ("LO:SM", "San Marino"),
	R_205 ("LO:SN", "Senegal"),
	R_206 ("LO:SO", "Somalia"),
	R_207 ("LO:SR", "Suriname"),
	R_208 ("LO:SS", "South Sudan"),
	R_209 ("LO:ST", "Sao Tome and Principe"),
	R_210 ("LO:SV", "El Salvador"),
	R_211 ("LO:SX", "Sint Maarten"),
	R_212 ("LO:SY", "Syria"),
	R_213 ("LO:SZ", "Swaziland"),
	R_214 ("LO:TC", "Turks and Caicos Islands"),
	R_215 ("LO:TD", "Chad"),
	R_216 ("LO:TF", "French Southern Lands"),
	R_217 ("LO:TG", "Togo"),
	R_218 ("LO:TH", "Thailand"),
	R_219 ("LO:TJ", "Tajikistan"),
	R_220 ("LO:TK", "Tokelau"),
	R_221 ("LO:TL", "Timor-Leste"),
	R_222 ("LO:TM", "Turkmenistan"),
	R_223 ("LO:TN", "Tunisia"),
	R_224 ("LO:TO", "Tonga"),
	R_225 ("LO:TR", "Turkey"),
	R_226 ("LO:TT", "Trinidad and Tobago"),
	R_227 ("LO:TV", "Tuvalu"),
	R_228 ("LO:TW", "Taiwan"),
	R_229 ("LO:TZ", "Tanzania"),
	R_230 ("LO:UA", "Ukraine"),
	R_231 ("LO:UG", "Uganda"),
	R_232 ("LO:UM", "United States Minor Outlying Islands"),
	R_233 ("LO:US", "United States of America"),
	R_234 ("LO:UY", "Uruguay"),
	R_235 ("LO:UZ", "Uzbekistan"),
	R_236 ("LO:VA", "Vatican City"),
	R_237 ("LO:VC", "Saint Vincent and the Grenadines"),
	R_238 ("LO:VE", "Venezuela"),
	R_239 ("LO:VG", "Virgin Islands, British"),
	R_240 ("LO:VI", "Virgin Islands, U.S."),
	R_241 ("LO:VN", "Vietnam"),
	R_242 ("LO:VU", "Vanuatu"),
	R_243 ("LO:WF", "Wallis and Futuna Islands"),
	R_244 ("LO:WS", "Samoa"),
	R_245 ("LO:YE", "Yemen"),
	R_246 ("LO:YT", "Mayotte"),
	R_247 ("LO:ZA", "South Africa"),
	R_248 ("LO:ZM", "Zambia"),
	R_249 ("LO:ZW", "Zimbabwe"),
	;

	private String key;
	private String value;
	
	public String getKey() {
		return key;
	}
	
	public KeyValueString getObject() {
		return new KeyValueString(key, value, new String[] {});
	}

	public static List<KeyValueString> getObjects() {
		List<KeyValueString> res = new ArrayList<>();
		for (ER1126Negara eEnum : ER1126Negara.values()) {
			res.add(eEnum.getObject());
		}
		return res;
	}
	
	public static String getName() {
		return ER1126Negara.class.getSimpleName().substring(6);
	}
	
	public static int getRefNumber() {
		return Integer.parseInt(ER1126Negara.class.getSimpleName().substring(2, 6));
	}
	
	public static String getPipedKey() {
		return UtilMetadata.genPipeRow(getObjects());
	}
	
	public static String getLookup() {
		StringBuilder res = new StringBuilder();
		ER1126Negara[] eEnums = ER1126Negara.values();
		int enumLength = eEnums.length;
		for (int i= 0; i < enumLength; i++) {
			ER1126Negara eEnum = ER1126Negara.values()[i];
			res.append(eEnum.key).append(":").append(eEnum.value);
			if (i + 1 < enumLength) {
				res.append("|");
			}
		}
		return res.toString();
	}
}
