package id.go.ojk.conf.client.field.reference;

import java.util.ArrayList;
import java.util.List;

import id.go.ojk.conf.client.UtilMetadata;
import id.go.ojk.lib.client.IObject;
import id.go.ojk.lib.client.model.KeyValueString;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum ER1151GolonganInvestor implements IObject<KeyValueString> {
	R_1 ("EN:e2953", "Kantor Pelayanan Perbendaharaan Negara (KPPN)"),
	R_2 ("EN:e2954", "Kementerian Keuangan"),
	R_3 ("EN:e2955", "Kementerian Pertahanan"),
	R_4 ("EN:e2956", "Kementerian Kehutanan"),
	R_5 ("EN:e2957", "Kementerian Pertanian"),
	R_6 ("EN:e2958", "Kementerian Pertambangan dan Energi"),
	R_7 ("EN:e2959", "Kementerian Agama"),
	R_8 ("EN:e2960", "Kementerian Negara BUMN"),
	R_9 ("EN:e1000", "Kementerian Kebudayaan, Pendidikan Dasar, dan Menengah"),
	R_10 ("EN:e1001", "Kementerian Pekerjaan Umum dan Perumahan Rakyat"),
	R_11 ("EN:e1002", "Kementerian Kesehatan"),
	R_12 ("EN:e1003", "Kementerian Perhubungan"),
	R_13 ("EN:e2961", "Kementerian lainnya"),
	R_14 ("EN:e2966", "Badan dan Lembaga Pemerintah"),
	R_15 ("EN:e1006", "Badan Layanan Umum - Kesehatan"),
	R_16 ("EN:e1007", "Badan Layanan Umum - Pendidikan"),
	R_17 ("EN:e1008", "Badan Layanan Umum Lainnya"),
	R_18 ("EN:e2967", "Badan Urusan Logistik (BULOG)"),
	R_19 ("EN:e1323", "Kementerian Pariwisata dan Ekonomi Kreatif"),
	R_20 ("EN:e1324", "Badan Pengelolaan Tabungan Perumahan Rakyat (BP-TAPERA)"),
	R_21 ("EN:e1325", "Komisi Pemberantasan Korupsi"),
	R_22 ("EN:e1326", "Majelis Permusyawaratan Rakyat (MPR)"),
	R_23 ("EN:e1327", "Dewan Perwakilan Rakyat (DPR)"),
	R_24 ("EN:e1328", "Badan Pemeriksa Keuangan (BPK)"),
	R_25 ("EN:e1329", "Mahkamah Agung (MA)"),
	R_26 ("EN:e1330", "Mahkamah Konstitusi (MK)"),
	R_27 ("EN:e1331", "Komisi Yudisial (KY)"),
	R_28 ("EN:e1332", "Dewan Perwakilan Daerah (DPD)"),
	R_29 ("EN:e2969", "Badan-badan dan Lembaga-lembaga Pemerintah Lainnya"),
	R_30 ("EN:e1013", "Jaminan Sosial Pemerintahan Umum"),
	R_31 ("EN:e1015", "Pemerintah Pusat - Pemerintahan Umum"),
	R_32 ("EN:e1016", "Pemerintah Federal - Pemerintahan Umum"),
	R_33 ("EN:e1038", "Bank Indonesia (Bank Sentral)"),
	R_34 ("EN:e1039", "Otoritas Jasa Keuangan (OJK)"),
	R_35 ("EN:e2968", "Lembaga Penjamin Simpanan (LPS)"),
	R_36 ("EN:e2963", "Pemerintah Provinsi"),
	R_37 ("EN:e2964", "Pemerintah Kota"),
	R_38 ("EN:e2965", "Pemerintah Kabupaten"),
	R_39 ("EN:e1010", "Badan Layanan Umum Daerah"),
	R_40 ("EN:e1011", "Propinsi"),
	R_41 ("EN:e1012", "Kota/Kabupaten"),
	R_42 ("EN:e1017", "Pemerintah Daerah- Pemerintahan Umum"),
	R_43 ("EN:e3151", "Pemerintah Pusat Negara Asing"),
	R_44 ("EN:e1186", "Pemerintah Daerah Negara Asing"),
	R_45 ("EN:e3248", "Islamic Development Bank (IDB)"),
	R_46 ("EN:e3249", "Asian Development Bank (ADB)"),
	R_47 ("EN:e3608", "World Bank"),
	R_48 ("EN:e1200", "African Development Bank Group (AfDB)"),
	R_49 ("EN:e1201", "European Bank for Reconstruction & Development (EBRD)"),
	R_50 ("EN:e1202", "Inter-American Development Bank Group (IADB)"),
	R_51 ("EN:e1203", "European Investment Bank (EIB)"),
	R_52 ("EN:e1204", "European Investment Fund (EIF)"),
	R_53 ("EN:e1205", "Nordic Investment Bank (NIB)"),
	R_54 ("EN:e1206", "Caribbean Development Bank (CDB)"),
	R_55 ("EN:e1207", "Council of Europe Development Bank (CEDB)"),
	R_56 ("EN:e1374", "International Monetary Fund (IMF)"),
	R_57 ("EN:e3261", "Bank pembangunan multilateral lainnya"),
	R_58 ("EN:e3609", "Lembaga Internasional Lainnya"),
	R_59 ("EN:e1208", "Lembaga Internasional Lainnya Lainnya"),
	R_60 ("EN:e3597", "BUMN Bank Umum Konvensional"),
	R_61 ("EN:e3598", "BUMN Bank Umum Syariah"),
	R_62 ("EN:e3599", "BUMN Bank Perkreditan Rakyat (BPR) Konvensional"),
	R_63 ("EN:e3600", "BUMN Bank Perkreditan Rakyat (BPR) Syariah"),
	R_64 ("EN:e3603", "Bank Umum Konvensional Swasta Nasional"),
	R_65 ("EN:e3604", "Bank Umum Syariah Swasta Nasional"),
	R_66 ("EN:e3605", "Bank Perkreditan Rakyat (BPR) Konvensional Swasta Nasional"),
	R_67 ("EN:e3606", "Bank Perkreditan Rakyat (BPR) Syariah Swasta Nasional"),
	R_68 ("EN:e1188", "Bank Sentral Negara Lain"),
	R_69 ("EN:e2485", "Bank Nasional yang Beroperasi di Luar Negeri"),
	R_70 ("EN:e1191", "Terkait Dengan Bank - Prime Bank"),
	R_71 ("EN:e1192", "Tidak Terkait Dengan Bank Negara Asing - Prime Bank"),
	R_72 ("EN:e1194", "Terkait Dengan Bank - Non Prime Bank"),
	R_73 ("EN:e1195", "Tidak Terkait Dengan Bank - Non Prime Bank"),
	R_74 ("EN:e2978", "Jamsostek"),
	R_75 ("EN:e2979", "Taspen"),
	R_76 ("EN:e2980", "Jiwasraya"),
	R_77 ("EN:e2981", "Jasa Raharja"),
	R_78 ("EN:e2982", "Jasindo"),
	R_79 ("EN:e2983", "ASABRI"),
	R_80 ("EN:e2984", "BUMN Asuransi Lainnya"),
	R_81 ("EN:e2985", "BUMN Perusahaan Dana Pensiun"),
	R_82 ("EN:e2987", "BUMN Modal Ventura"),
	R_83 ("EN:e2988", "BUMN Perusahaan Pembiayaan"),
	R_84 ("EN:e2990", "BUMN Perusahaan Sekuritas yang Tidak Melakukan Kegiatan Usaha Reksa Dana"),
	R_85 ("EN:e2991", "BUMN Perusahaan Sekuritas yang Melakukan Kegiatan Usaha Reksa Dana"),
	R_86 ("EN:e2992", "BUMN Perusahaan Reksa Dana"),
	R_87 ("EN:e2993", "BUMN Manajer Investasi"),
	R_88 ("EN:e2994", "Danareksa"),
	R_89 ("EN:e2995", "BUMN Perusahaan Sekuritas dan Reksa Dana Lainnya"),
	R_90 ("EN:e2997", "Perum Pegadaian"),
	R_91 ("EN:e2998", "Pos Indonesia"),
	R_92 ("EN:e2999", "Lembaga Pembiayaan Ekspor Indonesia"),
	R_93 ("EN:e3000", "BUMN Lembaga Keuangan Bukan Bank Lainnya Selain Perum Pegadaian, Pos Indonesia, dan LPEI"),
	R_94 ("EN:e3025", "BUMD Perusahaan Asuransi"),
	R_95 ("EN:e3026", "BUMD Perusahaan Dana Pensiun"),
	R_96 ("EN:e3027", "BUMD Modal Ventura"),
	R_97 ("EN:e3028", "BUMD Perusahaan Pembiayaan"),
	R_98 ("EN:e3030", "BUMD Perusahaan Sekuritas yang Tidak Melakukan Kegiatan Usaha Reksa Dana"),
	R_99 ("EN:e3031", "BUMD Perusahaan Sekuritas yang Melakukan Kegiatan Usaha Reksa Dana"),
	R_100 ("EN:e3032", "BUMD Perusahaan Reksa Dana"),
	R_101 ("EN:e3033", "BUMD Manajer Investasi"),
	R_102 ("EN:e3034", "BUMD Perusahaan Sekuritas dan Reksa Dana Lainnya"),
	R_103 ("EN:e3035", "BUMD Lembaga Keuangan Lainnya"),
	R_104 ("EN:e1041", "Korporasi penghimpunan simpanan LNP"),
	R_105 ("EN:e1042", "Korporasi penghimpunan simpanan LUP"),
	R_106 ("EN:e1044", "Korporasi penghimpun simpanan publik-LNP"),
	R_107 ("EN:e1045", "Korporasi penghimpun simpanan publik- LUP"),
	R_108 ("EN:e1047", "Korporasi penghimpun simpanan swasta nasional-LNP"),
	R_109 ("EN:e1048", "Korporasi penghimpun simpanan swasta nasional- LUP"),
	R_110 ("EN:e1050", "Korporasi penghimpun simpanan yang dikendalikan asing-LNP"),
	R_111 ("EN:e1051", "Korporasi penghimpun simpanan yang dikendalikan asing- LUP"),
	R_112 ("EN:e1053", "Pasar uang reksa dana - LNP"),
	R_113 ("EN:e1054", "Pasar uang reksa dana - LUP"),
	R_114 ("EN:e1056", "Pasar uang reksa dana publik - LNP"),
	R_115 ("EN:e1057", "Pasar uang reksa dana publik - LUP"),
	R_116 ("EN:e1059", "Pasar uang reksa dana swasta nasional - LNP"),
	R_117 ("EN:e1060", "Pasar uang reksa dana swasta nasional - LUP"),
	R_118 ("EN:e1062", "Pasar uang reksa dana yang dikendalikan asing- LNP"),
	R_119 ("EN:e1063", "Pasar uang reksa dana yang dikendalikan asing–LUP"),
	R_120 ("EN:e1065", "Dana investasi non-MMF –LNP"),
	R_121 ("EN:e1066", "Dana investasi non-MMF - LUP"),
	R_122 ("EN:e1068", "Dana investasi non-MMF publik - LNP"),
	R_123 ("EN:e1069", "Dana investasi non-MMF publik - LUP"),
	R_124 ("EN:e1071", "Dana investasi non-MMF swasta nasional - LNP"),
	R_125 ("EN:e1072", "Dana investasi non-MMF swasta nasional - LUP"),
	R_126 ("EN:e1074", "Dana investasi non-MMF yang dikendalikan asing- LNP"),
	R_127 ("EN:e1075", "Dana investasi non-MMF yang dikendalikan asing - LUP"),
	R_128 ("EN:e1077", "Penunjang keuangan - LNP"),
	R_129 ("EN:e1078", "Penunjang keuangan - LUP"),
	R_130 ("EN:e1080", "Penunjang keuangan publik -LNP"),
	R_131 ("EN:e1081", "Penunjang keuangan publik - LUP"),
	R_132 ("EN:e1082", "Penunjang Keuangan Publik - BUMN"),
	R_133 ("EN:e1083", "Penunjang Keuangan Publik - BUMD"),
	R_134 ("EN:e1084", "Penunjang Keuangan Publik - BUM Desa"),
	R_135 ("EN:e1086", "Penunjang keuangan swasta nasional- LNP"),
	R_136 ("EN:e1087", "Penunjang keuangan swasta nasional- LUP"),
	R_137 ("EN:e1088", "Penyelenggara Teknologi Finansial Swasta Nasional"),
	R_138 ("EN:e1089", "Penerbit Uang Elektronik Swasta Nasional"),
	R_139 ("EN:e1090", "Penunjang Keuangan Swasta Nasional Lainnya"),
	R_140 ("EN:e1092", "Penunjang keuangan yang dikendalikan asing- LNP"),
	R_141 ("EN:e1093", "Penunjang keuangan yang dikendalikan asing- LUP"),
	R_142 ("EN:e1094", "Penyelenggara Teknologi Finansial"),
	R_143 ("EN:e1095", "Penerbit Uang Elektronik"),
	R_144 ("EN:e1096", "Penunjang Keuangan yang dikendalikan asing Lainnya"),
	R_145 ("EN:e1098", "Lembaga keuangan captive- LNP"),
	R_146 ("EN:e1099", "Lembaga keuangan captive- LUP"),
	R_147 ("EN:e1101", "Lembaga keuangan captive publik - LNP"),
	R_148 ("EN:e1102", "Lembaga keuangan captive publik - LUP"),
	R_149 ("EN:e1104", "Lembaga keuangan captive swasta nasional - LNP"),
	R_150 ("EN:e1105", "Lembaga keuangan captive swasta nasional - LUP"),
	R_151 ("EN:e1107", "Lembaga keuangan captive yang dikendalikan asing- LNP"),
	R_152 ("EN:e1108", "Lembaga keuangan captive yang dikendalikan asing-LUP"),
	R_153 ("EN:e1110", "Korporasi asuransi - LNP"),
	R_154 ("EN:e1111", "Korporasi asuransi - LUP"),
	R_155 ("EN:e1113", "Korporasi asuransi publik - LNP"),
	R_156 ("EN:e1114", "Korporasi asuransi publik - LUP"),
	R_157 ("EN:e1115", "Korporasi asuransi - BUMN"),
	R_158 ("EN:e1116", "Korporasi asuransi - BUMD"),
	R_159 ("EN:e1117", "Korporasi asuransi - BUM Desa"),
	R_160 ("EN:e1119", "Korporasi asuransi swasta nasional- LNP"),
	R_161 ("EN:e1120", "Korporasi asuransi swasta nasional- LUP"),
	R_162 ("EN:e1122", "Korporasi asuransi yang dikendalikan asing- LNP"),
	R_163 ("EN:e1123", "Korporasi asuransi yang dikendalikan asing- LUP"),
	R_164 ("EN:e1124", "Dana Pensiun"),
	R_165 ("EN:e1125", "Dana Pensiun - LNP"),
	R_166 ("EN:e1128", "Dana pensiun publik- LNP"),
	R_167 ("EN:e1129", "Dana pensiun publik- LU"),
	R_168 ("EN:e1130", "Dana Pensiun Publik BUMN"),
	R_169 ("EN:e1131", "Dana Pensiun Publik BUMD"),
	R_170 ("EN:e1132", "Dana Pensiun Publik BUM Desa"),
	R_171 ("EN:e1134", "Dana pensiun swasta nasional- LNP"),
	R_172 ("EN:e1135", "Dana pensiun swasta nasional- LUP"),
	R_173 ("EN:e1137", "Dana pensiun yang dikendalikan asing- LNP"),
	R_174 ("EN:e1138", "Dana pensiun yang dikendalikan asing- LUP"),
	R_175 ("EN:e1140", "Korporasi finansial lain - LNP"),
	R_176 ("EN:e1141", "Korporasi finansial lain- LUP"),
	R_177 ("EN:e1143", "Korporasi finansial lain publik - LNP"),
	R_178 ("EN:e1144", "Korporasi finansial lain publik - LUP"),
	R_179 ("EN:e1146", "Korporasi finansial lain publik BUMN - Modal Ventura"),
	R_180 ("EN:e1147", "Korporasi finansial lain publik BUMN - Perusahaan Pembiayaan"),
	R_181 ("EN:e1149", "Korporasi finansial lain publik BUMN - Perusahaan sekuritas yang tidak melakukan kegiatan usaha reksadana"),
	R_182 ("EN:e1150", "Korporasi finansial lain publik BUMN - Perusahaan sekuritas yang melakukan kegiatan usaha reksadana"),
	R_183 ("EN:e1151", "Korporasi finansial lain publik BUMN - Perusahaan reksadana"),
	R_184 ("EN:e1152", "Korporasi finansial lain publik BUMN - Manajer Investasi"),
	R_185 ("EN:e1153", "Korporasi finansial lain publik BUMN - Lainnya"),
	R_186 ("EN:e1154", "Korporasi finansial lain Publik - Lainnya"),
	R_187 ("EN:e1156", "Korporasi finansial lain publik BUMD - Modal Ventura"),
	R_188 ("EN:e1157", "Korporasi finansial lain publik BUMD - Perusahaan Pembiayaan"),
	R_189 ("EN:e1158", "Korporasi finansial lain publik BUMD - Perusahaan Sekuritas dan Reksadana"),
	R_190 ("EN:e1159", "Korporasi finansial lain publik BUMD - Perusahaan sekuritas yang tidak melakukan kegiatan usaha reksadana"),
	R_191 ("EN:e1160", "Korporasi finansial lain publik BUMD - Perusahaan sekuritas yang melakukan kegiatan usaha reksadana"),
	R_192 ("EN:e1161", "Korporasi finansial lain publik BUMD - Perusahaan reksadana"),
	R_193 ("EN:e1162", "Korporasi finansial lain publik BUMD - Manajer Investasi"),
	R_194 ("EN:e1163", "Korporasi finansial lain publik BUMD - Lainnya"),
	R_195 ("EN:e1164", "Perusahaan Finansial Lainnya - Lainnya"),
	R_196 ("EN:e1165", "Korporasi finansial lain publik - BUM Desa"),
	R_197 ("EN:e1166", "Korporasi finansial lain swasta nasional - LNP"),
	R_198 ("EN:e1167", "Korporasi finansial lain swasta nasional - LUP"),
	R_199 ("EN:e3042", "Perusahaan Asuransi Swasta Nasional"),
	R_200 ("EN:e3043", "Perusahaan Dana Pensiun Swasta Nasional"),
	R_201 ("EN:e3044", "Modal Ventura Swasta Nasional"),
	R_202 ("EN:e3045", "Perusahaan Pembiayaan Swasta Nasional"),
	R_203 ("EN:e3047", "Perusahaan Sekuritas Swasta Nasional yang Tidak Melakukan Kegiatan Usaha Reksa Dana"),
	R_204 ("EN:e3048", "Perusahaan Sekuritas Swasta Nasional yang Melakukan Kegiatan Usaha Reksa Dana"),
	R_205 ("EN:e3049", "Perusahaan Reksa Dana Swasta Nasional"),
	R_206 ("EN:e3050", "Manajer Investasi Swasta Nasional"),
	R_207 ("EN:e3051", "Perusahaan Sekuritas dan Reksa Dana Swasta Nasional Lainnya"),
	R_208 ("EN:e1358", "Fintech P2P"),
	R_209 ("EN:e1359", "Fintech P2P Syariah"),
	R_210 ("EN:e1360", "Lembaga Pembiayaan - Swasta Nasional"),
	R_211 ("EN:e1361", "Perusahaan Pembiayaan Syariah - Swasta Nasional"),
	R_212 ("EN:e1362", "Perusahaan Modal Ventura - Swasta Nasional"),
	R_213 ("EN:e1363", "Perusahaan Modal Ventura Syariah - Swasta Nasional"),
	R_214 ("EN:e1364", "Perusahaan Pembiayaan Infrastruktur - Swasta Nasional"),
	R_215 ("EN:e1365", "Perusahaan Pembiayaan Infrastruktur Syariah - Swasta Nasional"),
	R_216 ("EN:e1366", "Secondary mortgage facility (SMF)"),
	R_217 ("EN:e1367", "PNM"),
	R_218 ("EN:e1368", "Lembaga Keuangan Mikro"),
	R_219 ("EN:e1369", "Lembaga Swasta Lainnya"),
	R_220 ("EN:e3053", "Baitul Maal Wa Tamwil (BMT) Swasta Nasional"),
	R_221 ("EN:e3055", "Koperasi Simpan Pinjam Primer"),
	R_222 ("EN:e3056", "Koperasi Simpan Pinjam Lainnya"),
	R_223 ("EN:e1168", "Lembaga Keuangan Bukan Bank Swasta Nasional Lainnya - Lainnya"),
	R_224 ("EN:e3057", "LKNB Swasta Nasional Lainnya selain Baitul Maal Wa Tamwil (BMT) dan Koperasi Simpan Pinjam"),
	R_225 ("EN:e3064", "Perusahaan Asuransi Campuran"),
	R_226 ("EN:e3065", "Perusahaan Dana pensiun Campuran"),
	R_227 ("EN:e3066", "Modal Ventura Campuran"),
	R_228 ("EN:e3067", "Perusahaan Pembiayaan Campuran"),
	R_229 ("EN:e3069", "Perusahaan Sekuritas Campuran yang Tidak Melakukan Kegiatan Usaha Reksa Dana"),
	R_230 ("EN:e3070", "Perusahaan Sekuritas Campuran yang Melakukan Kegiatan Usaha Reksa Dana"),
	R_231 ("EN:e3071", "Perusahaan Reksa Dana Campuran"),
	R_232 ("EN:e3072", "Manajer Investasi Campuran"),
	R_233 ("EN:e3073", "Perusahaan Sekuritas dan Reksa Dana Campuran Lainnya"),
	R_234 ("EN:e3075", "Baitul Maal Wa Tamwil (BMT) Campuran"),
	R_235 ("EN:e3076", "Kantor Perwakilan Lembaga Keuangan Bukan Bank Milik Asing di Indonesia yang Dimiliki Campuran"),
	R_236 ("EN:e3077", "Lembaga Keuangan Bukan Bank Campuran Lainnya selain Baitul Maal Wa Tamwil (BMT) Campuran dan Kantor Perwakilan Lembaga Keuangan Bukan Bank Milik Asing di Indonesia yang Dimiliki Campuran"),
	R_237 ("EN:e1169", "Korporasi finansial lain yang dikendalikan asing- LNP"),
	R_238 ("EN:e1170", "Korporasi finansial lain yang dikendalikan asing- LUP"),
	R_239 ("EN:e3081", "Perusahaan Asuransi di Luar Indonesia"),
	R_240 ("EN:e3082", "Dana pensiun Asing"),
	R_241 ("EN:e3083", "Modal Ventura Asing"),
	R_242 ("EN:e3084", "Perusahaan Pembiayaan Asing"),
	R_243 ("EN:e3086", "Perusahaan Sekuritas Asing yang Tidak Melakukan Kegiatan Usaha Reksa Dana"),
	R_244 ("EN:e3087", "Perusahaan Sekuritas Asing yang Melakukan Kegiatan Usaha Reksa Dana"),
	R_245 ("EN:e3088", "Perusahaan Reksa Dana Asing"),
	R_246 ("EN:e3089", "Manajer Investasi Asing"),
	R_247 ("EN:e3090", "Perusahaan Sekuritas dan Reksa Dana Asing lainnya"),
	R_248 ("EN:e3092", "Baitul Maal Wa Tamwil (BMT) Asing"),
	R_249 ("EN:e3093", "Kantor Perwakilan Lembaga Keuangan Bukan Bank Milik Asing di Indonesia Lainnya"),
	R_250 ("EN:e3094", "Lembaga Keuangan Bukan Bank Asing Lainnya selain Baitul Maal Wa Tamwil (BMT) Asing dan Kantor Perwakilan Lembaga Keuangan Bukan Bank di Indonesia Lainnya"),
	R_251 ("EN:e1171", "Perusahaan Sekuritas dan Reksadana Lainnya"),
	R_252 ("EN:e3154", "Lembaga Keuangan Bukan Bank yang Beroperasi di Luar Indonesia"),
	R_253 ("EN:e1196", "Lembaga Keuangan Bukan Bank Milik Negara Asing"),
	;

	private String key;
	private String value;
	
	public String getKey() {
		return key;
	}
	
	public KeyValueString getObject() {
		return new KeyValueString(key, value, new String[] {});
	}

	public static List<KeyValueString> getObjects() {
		List<KeyValueString> res = new ArrayList<>();
		for (ER1151GolonganInvestor eEnum : ER1151GolonganInvestor.values()) {
			res.add(eEnum.getObject());
		}
		return res;
	}
	
	public static String getName() {
		return ER1151GolonganInvestor.class.getSimpleName().substring(6);
	}
	
	public static int getRefNumber() {
		return Integer.parseInt(ER1151GolonganInvestor.class.getSimpleName().substring(2, 6));
	}
	
	public static String getPipedKey() {
		return UtilMetadata.genPipeRow(getObjects());
	}
	
	public static String getLookup() {
		StringBuilder res = new StringBuilder();
		ER1151GolonganInvestor[] eEnums = ER1151GolonganInvestor.values();
		int enumLength = eEnums.length;
		for (int i= 0; i < enumLength; i++) {
			ER1151GolonganInvestor eEnum = ER1151GolonganInvestor.values()[i];
			res.append(eEnum.key).append(":").append(eEnum.value);
			if (i + 1 < enumLength) {
				res.append("|");
			}
		}
		return res.toString();
	}
}
