package id.go.ojk.conf.client.field.reference;

import java.util.ArrayList;
import java.util.List;

import id.go.ojk.lib.client.IObject;
import id.go.ojk.lib.client.model.KeyValueString;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum ER1220CounterParty implements IObject<KeyValueString> {
  R1 ("10", "Kantor Perbendaharaan dan Kas Negara (KPKN) - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R2 ("20", "Kementerian Keuangan - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R3 ("30", "Kementerian Pertahanan - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R4 ("40", "Kementerian Kehutanan - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R5 ("50", "Kementerian Pertanian - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R6 ("60", "Kementerian Pertambangan dan Energi - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R7 ("70", "Kementerian Agama - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R8 ("80", "Kementerian Negara BUMN - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R9 ("999", "Kementerian lainnya - Pemerintah Pusat - Sektor Pemerintah - Penduduk"),
  R10 ("1010", "Provinsi - Pemerintah Daerah (Pemda) - Sektor Pemerintah - Penduduk"),
  R11 ("1020", "Pemerintah Kota - Pemerintah Daerah (Pemda) - Sektor Pemerintah - Penduduk"),
  R12 ("1030", "Pemerintah Kabupaten - Pemerintah Daerah (Pemda) - Sektor Pemerintah - Penduduk"),
  R13 ("2010", "Badan Urusan Logistik (BULOG) - Badan-badan dan Lembaga-lembaga Pemerintah - Sektor Pemerintah - Penduduk"),
  R14 ("2020", "Lembaga Penjamin Simpanan (LPS) - Badan-badan dan Lembaga-lembaga Pemerintah - Sektor Pemerintah - Penduduk"),
  R15 ("2090", "Lainnya - Badan-badan dan Lembaga-lembaga Pemerintah - Sektor Pemerintah - Penduduk"),
  R16 ("6110", "Bank Umum Konvensional - Lembaga Keuangan Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R17 ("6120", "Bank Umum Syariah - Lembaga Keuangan Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R18 ("6130", "Bank Perkreditan Rakyat (BPR) Konvensional - Lembaga Keuangan Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R19 ("6140", "Bank Perkreditan Rakyat (BPR) Syariah - Lembaga Keuangan Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R20 ("4111", "Asuransi : Jamsostek - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R21 ("4112", "Taspen - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R22 ("4113", "Jiwasraya - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R23 ("4114", "Jasa Raharja - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R24 ("4115", "Jasindo - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R25 ("4116", "ASABRI - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R26 ("4119", "Perusahaan asuransi lainnya - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R27 ("4120", "Dana Pensiun - Perusahaan Asuransi dan Dana Pensiun -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R28 ("4130", "Modal Ventura -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R29 ("4140", "Perusahaan Pembiayaan -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R30 ("4151", "Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R31 ("4152", "Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R32 ("4153", "Perusahaan Reksadana - Perusahaan Sekuritas dan Reksadana -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R33 ("4154", "Manajer Investasi - Perusahaan Sekuritas dan Reksadana -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R34 ("4155", "PT Danareksa - Perusahaan Sekuritas dan Reksadana -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R35 ("4159", "Lainnya - Perusahaan Sekuritas dan Reksadana -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R36 ("4171", "Perum Pegadaian - Lembaga Keuangan Non Bank Lainnya -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R37 ("4172", "PT Pos Indonesia - Lembaga Keuangan Non Bank Lainnya -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R38 ("4179", "Lainnya - Lembaga Keuangan Non Bank Lainnya -  Lembaga Keuangan Non Bank - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R39 ("4501", "PT Kereta Api Indonesia (KAI) - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R40 ("4502", "PT Pelayaran Nasional Indonesia (PELNI) - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R41 ("4503", "PT Pelabuhan Laut Indonesia (PELINDO) - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R42 ("4504", "PT Angkutan Sungai, Danau dan Penyeberangan (ASDP) - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R43 ("4505", "PT Angkasa Pura - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R44 ("4506", "PT Perkebunan Nusantara - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R45 ("4507", "PT Pertamina - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R46 ("4508", "PT Perusahaan Listrik Negara (PLN) - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R47 ("4509", "PT Krakatau Steel - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R48 ("4510", "PT Garuda Indonesia - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R49 ("4511", "PT Telkom - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R50 ("4512", "PT Indosat - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R51 ("4513", "PT Jasa Marga - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R52 ("4514", "PT Timah - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R53 ("4515", "PT Aneka Tambang - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R54 ("4516", "Perusahaan Jasa Kontruksi - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R55 ("4599", "Lainnya - Bukan Lembaga Keuangan - Badan Usaha Milik Negara (BUMN) atau Pemerintah Campuran - Sektor Pemerintah - Penduduk"),
  R56 ("5110", "Perusahaan Asuransi - Perusahaan Asuransi dan Dana Pensiun - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R57 ("5120", "Dana Pensiun - Perusahaan Asuransi dan Dana Pensiun - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R58 ("5130", "Modal Ventura - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R59 ("5140", "Perusahaan Pembiayaan - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R60 ("5151", "Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R61 ("5152", "Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R62 ("5153", "Perusahaan Reksadana - Perusahaan Sekuritas dan Reksadana - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R63 ("5154", "Manajer Investasi - Perusahaan Sekuritas dan Reksadana - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R64 ("5159", "Lainnya - Perusahaan Sekuritas dan Reksadana - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R65 ("5199", " -  - Perusahaan Sekuritas dan Reksadana - Lembaga Keuangan Non Bank - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R66 ("5501", "Perusahaan Daerah Air Minum (PDAM) - Bukan Lembaga Keuangan - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R67 ("5502", "Perusahaan Daerah Pasar (PD Pasar) - Bukan Lembaga Keuangan - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R68 ("5599", "Lainnya - Bukan Lembaga Keuangan - Badan Usaha Milik Daerah (BUMD) - Sektor Pemerintah - Penduduk"),
  R69 ("6110", "Bank Umum Konvensional - Lembaga Keuangan Bank - Sektor Swasta - Penduduk"),
  R70 ("6120", "Bank Umum Syariah - Lembaga Keuangan Bank - Sektor Swasta - Penduduk"),
  R71 ("6130", "Bank Perkreditan Rakyat (BPR) Konvensional - Lembaga Keuangan Bank - Sektor Swasta - Penduduk"),
  R72 ("6140", "Bank Perkreditan Rakyat (BPR) Syariah - Lembaga Keuangan Bank - Sektor Swasta - Penduduk"),
  R73 ("7110", "Perusahaan Asuransi - Perusahaan Asuransi dan Dana Pensiun - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R74 ("7120", "Dana Pensiun - Perusahaan Asuransi dan Dana Pensiun - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R75 ("7130", "Modal Ventura - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R76 ("7140", "Perusahaan Pembiayaan - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R77 ("7151", "Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R78 ("7152", "Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R79 ("7153", "Perusahaan Reksadana - Perusahaan Sekuritas dan Reksadana - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R80 ("7154", "Manajer Investasi - Perusahaan Sekuritas dan Reksadana - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R81 ("7159", "Lainnya - Perusahaan Sekuritas dan Reksadana - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R82 ("7172", "Baitul Maal Wa Tamwil (BMT) - Lembaga Keuangan Non Bank Lainnya - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R83 ("7173", "Koperasi Primer - Koperasi Simpan Pinjam - Lembaga Keuangan Non Bank Lainnya - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R84 ("7174", "Koperasi Lainnya - Koperasi Simpan Pinjam - Lembaga Keuangan Non Bank Lainnya - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R85 ("7190", "Lainnya - Lembaga Keuangan Non Bank Lainnya - Swasta Nasional - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk7210 - Perusahaan Asuransi - Perusahaan Asuransi dan Dana Pensiun - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R86 ("7220", "Dana Pensiun - Perusahaan Asuransi dan Dana Pensiun - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R87 ("7230", "Modal Ventura - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R88 ("7240", "Perusahaan Pembiayaan - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R89 ("7251", "Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R90 ("7252", "Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R91 ("7253", "Perusahaan Reksadana - Perusahaan Sekuritas dan Reksadana - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R92 ("7254", "Manajer Investasi - Perusahaan Sekuritas dan Reksadana - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R93 ("7259", "Lainnya - Perusahaan Sekuritas dan Reksadana - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R94 ("7272", "Baitul Maal Wa Tamwil (BMT) - Lembaga Keuangan Non Bank Lainnya - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R95 ("7273", "Kantor Perwakilan Lembaga Milik Asing di Indonesia - Lembaga Keuangan Non Bank Lainnya - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R96 ("7290", "Lainnya - Lembaga Keuangan Non Bank Lainnya - Campuran - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk7310 - Perusahaan Asuransi - Perusahaan Asuransi dan Dana Pensiun - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R97 ("7320", "Dana Pensiun - Perusahaan Asuransi dan Dana Pensiun - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R98 ("7330", " - Perusahaan Asuransi dan Dana Pensiun - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R99 ("7340", " - Perusahaan Asuransi dan Dana Pensiun - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R100 ("7351", "Perusahaan sekuritas yang tidak melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R101 ("7352", "Perusahaan sekuritas yang melakukan kegiatan usaha Reksadana - Perusahaan Sekuritas dan Reksadana - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R102 ("7353", "Perusahaan Reksadana - Perusahaan Sekuritas dan Reksadana - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R103 ("7354", "Manajer Investasi - Perusahaan Sekuritas dan Reksadana - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R104 ("7359", "Lainnya - Perusahaan Sekuritas dan Reksadana - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R105 ("7372", "Baitul Maal Wa Tamwil (BMT) - Lembaga Keuangan Non Bank Lainnya - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R106 ("7379", "Kantor Perwakilan Lembaga Milik Asing di Indonesia lainnya - Lembaga Keuangan Non Bank Lainnya - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R107 ("7390", "Lainnya - Lembaga Keuangan Non Bank Lainnya - Asing - Lembaga Keuangan Non Bank - Sektor Swasta - Penduduk"),
  R108 ("8111", "Perusahaan Otomotif - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R109 ("8112", "Perusahaan Perminyakan - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R110 ("8113", "Perusahaan Tekstil - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R111 ("8114", "Perusahaan Perkayuan (HPH) - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R112 ("8115", "Perusahaan Jasa Konstruksi - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R113 ("8116", "Perusahaan Industri Rokok - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R114 ("8117", "Perusahaan Industri Makanan - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R115 ("8118", "Perusahaan Agrobusiness - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R116 ("8139", "Perusahaan Lainnya - Perusahaan-perusahaan lainnya - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R117 ("8141", "Koperasi Primer - Koperasi Bukan Simpan Pinjam - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R118 ("8149", "Koperasi Lainnya - Koperasi Bukan Simpan Pinjam - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R119 ("8151", "Badan Amil Zakat Infaq dan Shadaqah (BAZIS) - Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R120 ("8152", "Lembaga Pendidikan - Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R121 ("8159", "Lainnya - Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Swasta Nasional - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk8411 - Perusahaan Otomotif - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R122 ("8412", "Perusahaan Perminyakan - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R123 ("8413", "Perusahaan Tekstil - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R124 ("8414", "Perusahaan Perkayuan (HPH) - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R125 ("8415", "Perusahaan Jasa Konstruksi - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R126 ("8416", "Perusahaan Industri Rokok - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R127 ("8417", "Perusahaan Industri Makanan - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R128 ("8418", "Perusahaan Agrobusiness - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R129 ("8449", "Perusahaan Lainnya - Perusahaan-perusahaan lainnya - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R130 ("8451", "Badan Amil Zakat Infaq dan Shadaqah (BAZIS) - Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R131 ("8452", "Lembaga Pendidikan - Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R132 ("8469", "Lainnya - Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R133 ("8480", "Kantor Perwakilan Lembaga Milik Asing di Indonesia - Campuran - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk8611 - Perusahaan Otomotif -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R134 ("8612", "Perusahaan Perminyakan -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R135 ("8613", "Perusahaan Tekstil -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R136 ("8614", "Perusahaan Perkayuan (HPH) -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R137 ("8615", "Perusahaan Jasa Konstruksi -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R138 ("8616", "Perusahaan Industri Rokok -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R139 ("8617", "Perusahaan Industri Makanan -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R140 ("8618", "Perusahaan Agrobusiness -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R141 ("8619", "Perusahaan Lainnya -  Perusahaan-perusahaan lainnya - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R142 ("8651", "Badan Amil Zakat Infaq dan Shadaqah (BAZIS) -  Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R143 ("8652", "Lembaga Pendidikan -  Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R144 ("8659", "Lainnya -  Yayasan, Badan Sosial dan Organisasi Kemasyarakatan - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R145 ("8670", "Kantor Perwakilan Lembaga Milik Asing di Indonesia - Asing - Bukan Lembaga Keuangan - Sektor Swasta - Penduduk"),
  R146 ("8900", "Sektor Swasta Lainnya - Sektor Swasta - Penduduk"),
  R147 ("9000", "Perseorangan - Sektor Swasta - Penduduk"),
  R148 ("9100", "Pemerintah pusat - Bukan Penduduk"),
  R149 ("9200", "Perwakilan negara-negara asing dan stafnya - Bukan Penduduk"),
  R150 ("9300", "BUMN Milik Negara Asing - Bukan Penduduk"),
  R151 ("9400", "Lembaga-lembaga keuangan bukan bank yang beroperasi di luar Indonesia - Bukan Penduduk"),
  R152 ("9501", "Swasta Patungan Indonesia dan Negara Asing - Swasta Lainnya - Bukan Penduduk"),
  R153 ("9502", "Swasta Milik Indonesia - Swasta Lainnya - Bukan Penduduk"),
  R154 ("9519", "Lainnya - Swasta Lainnya - Bukan Penduduk9611 - Islamic Development Bank (ADB) - Bank Pembangunan Multilateral - Lembaga-Lembaga Internasional - Bukan Penduduk"),
  R155 ("9612", "Asian Development Bank (ADB) - Bank Pembangunan Multilateral - Lembaga-Lembaga Internasional - Bukan Penduduk"),
  R156 ("9613", "World Bank - Bank Pembangunan Multilateral - Lembaga-Lembaga Internasional - Bukan Penduduk"),
  R157 ("9629", "Lainnya - Bank Pembangunan Multilateral - Lembaga-Lembaga Internasional - Bukan Penduduk"),
  R158 ("9690", "Lainnya - Lembaga-Lembaga Internasional - Bukan Penduduk"),
  R159 ("9700", "Perseorangan - Bukan Penduduk"),
  ;

  private String key;
  private String value;

  public KeyValueString getObject() {
    return new KeyValueString(key, value, new String[] {});
  }

  public static List<KeyValueString> getObjects() {
    List<KeyValueString> res = new ArrayList<>();
    for (ER1220CounterParty eEnum : ER1220CounterParty.values()) {
      res.add(eEnum.getObject());
    }
    return res;
  }

  public static String getName() {
    return ER1220CounterParty.class.getSimpleName().substring(6);
  }

  public static int getRefNumber() {
    return Integer.parseInt(ER1220CounterParty.class.getSimpleName().substring(2, 6));
  }
}
