package id.go.ojk.asrjs.client.builder.field;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum EFormLaporanBulanan {
	LB_000 ("000", "Profil Perusahaan"),
	LB_001 ("001", "Rincian Pemegang Saham"),
	LB_002 ("002", "Rincian Pihak Utama"),
	LB_003 ("003", "Rasio Pendidikan dan Pelatihan - I"),
	LB_004 ("004", "Rasio Pendidikan dan Pelatihan - II"),
	LB_910 ("910", "Surat Pernyataan"),
	LB_100 ("100", "Laporan Posisi Keuangan"),
	LB_200 ("200", "Laporan Kinerja Keuangan"),
	LB_300 ("300", "PERHITUNGAN ARUS KAS"),
	LB_400 ("400", "LAPORAN PERUBAHAN DANA"),
	LB_500 ("500", "ANALISIS DANA PERUSAHAAN - PERHITUNGAN ASET DAN LIABILITAS SAP DANA PERUSAHAAN"),
	LB_501 ("501", "ANALISIS DANA PERUSAHAAN - PERHITUNGAN LIABILITAS SAP DANA PERUSAHAAN"),
	LB_600 ("600", "ANALISIS DANA TABARRU' DAN TANAHUD - PERHITUNGAN ASET DAN LIABILITAS DANA TABARRU' DAN TANAHUD"),
	LB_601 ("601", "ANALISIS DANA TABARRU' DAN TANAHUD - PERHITUNGAN ASET DAN LIABILITAS DANA TABARRU'"),
	LB_700 ("700", "ANALISIS DANA INVESTASI PERSERTA - PERHITUNGAN ASET DAN LIABILITAS DANA INVESTASI PESERTA"),
	LB_701 ("701", "ANALISIS DANA INVESTASI PERSERTA - PERHITUNGAN LIABILITAS DIP PADA PAYDI YANG DIGARANSI"),
	LB_110 ("110", "PENCAPAIAN TINGKAT SOLVABILITAS - LAPORAN KEUANGAN"),
	LB_111 ("111", "RASIO KEUANGAN SELAIN TINGKAT SOLVABILITAS - LAPORAN KEUANGAN"),
	LB_210 ("210", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO KREDIT"),
	LB_211 ("211", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO KREDIT - RISIKO KEGAGALAN ATAU KETIDAKMAMPUAN DEBITUR ATAU PIHAK LAIN"),
	LB_212 ("212", "DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO KREDIT - KEGAGALAN/KETIDAKMAMPUAN PENANGGUNG ULANG"),
	LB_213 ("213", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO LIABILITAS"),
	LB_214 ("214", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO PASAR"),
	LB_215 ("215", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO PASAR - PERUBAHAN HARGA PASAR"),
	LB_216 ("216", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO PASAR - PERUBAHAN NILAI TUKAR MATA UANG ASING"),
	LB_217 ("217", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO PASAR - RISIKO PERUBAHAN TINGKAT HASIL INVESTASI"),
	LB_218 ("218", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO ASURANSI"),
	LB_219 ("219", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO ASURANSI - PENYISIHAN KONTRIBUSI"),
	LB_220 ("220", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO ASURANSI - PENYISIHAN ATAS KONTRIBUSI YANG BELUM MERUPAKAN PENDAPATAN"),
	LB_221 ("221", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO ASURANSI - PENYISIHAN KLAIM"),
	LB_222 ("222", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO ASURANSI - PENYISIHAN ATAS RISIKO BENCANA"),
	LB_223 ("223", "MODAL MINIMUM BERBASIS RISIKO DAN DANA TABARRU MINIMUM BERBASIS RISIKO - RISIKO OPERASIONAL"),
	LB_224 ("224", "RINCIAN A-110. Rincian Investasi dan Property"),
	LB_225 ("225", "RINCIAN A-120. Rincian Tagihan"),
	LB_226 ("226", "RINCIAN A-130. Rincian Aset Lain"),
	LB_227 ("227", "RINCIAN A-210. Rincian Utang - Laporan Keuangan"),
	LB_228 ("228", "RINCIAN A-220. Penyisihan Kontribusi - Laporan Keuangan"),
	LB_232 ("232", "RINCIAN A-230 Penyisihan Atas Kontribusi Yang Belum Merupakan Pendapatan - Laporan Keuangan"),
	LB_229 ("229", "RINCIAN A-240. Rincian Penyisihan Klaim"),
	LB_230 ("230", "RINCIAN A-250. PENYISIHAN ATAS RISIKO BENCANA (CATASTROPHIC RISK)"),
	LB_231 ("231", "RINCIAN A-310. Rincian Rekapitulasi Aset dan Liabilitas Berdasarkan Mata Uang dan Umur Jatuh Tempo"),
	LB_233 ("233", "RINCIAN B-110. Kontribusi dan Klaim Berdasarkan Lini Usaha"),
	LB_234 ("234", "RINCIAN C-110. LAPORAN DANA JAMINAN - Ringkasan Perkembangan Dana Jaminan dan Perhitungan Kecukupan Dana Jaminan"),
	LB_604 ("604", "RINCIAN D-110. Komposisi Kontribusi dan Loading Produk Asuransi Tradisional"),
	LB_605 ("605", "RINCIAN D-120. KOMPOSISI KONTRIBUSI DAN LOADING PRODUK ASURANSI DENGAN INVESTASI"),
	LB_606 ("606", "RINCIAN D-130. Perkembangan Portofolio Pertanggungan Perorangan"),
	LB_607 ("607", "RINCIAN D-140. Perkembangan Portofolio Pertanggungan Kumpulan"),
	LB_608 ("608", "RINCIAN E-110. Penyisihan Kontribusi Pertanggungan"),
	LB_609 ("609", "Rincian E-120. Penyisihan Kontribusi Produk Kecelakaan, Kesehatan, Ekawarsa"),
	LB_610 ("610", "Rincian E-130. Penyisihan Kontribusi Produk Investasi"),
	LB_616 ("616", "RINCIAN F-110. Reasuransi Keluar"),
	LB_235 ("235", "RINCIAN G-110. Kinerja Pemasaran Asuransi Mikro Per Jenis Produk Asuransi"),
	LB_236 ("236", "RINCIAN G-120. Kinerja Saluran Pemasaran Asuransi Mikro"),
	;
	
	@Getter
	private String code;
	@Getter
	private String name;
}
