#OJKClient
#Fri Mar 25 07:59:38 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPS\\error-validasi-server\\hasil
proxyPort=8080
