package id.go.ojk.client.module.apu;

import id.go.ojk.client.constant.EReport;
import id.go.ojk.client.model.ReportInfo;

public enum EReportApu {
	ASRJK_PENILAIAN_RUTIN ("TAPUAJK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_ASRJK),
	ASRJK_PENILAIAN_KOREKSI ("TAPUAJK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_ASRJK),
	ASRJK_RENCANA_RUTIN ("KAPUAJK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_ASRJK),
	ASRJK_RENCANA_KOREKSI ("KAPUAJK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_ASRJK),
	ASRJK_REALISASI_RUTIN ("PAPUAJK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_ASRJK),
	ASRJK_REALISASI_KOREKSI ("PAPUAJK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_ASRJK),

	ASRUK_PENILAIAN_RUTIN ("TAPUAUK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_ASRUK),
	ASRUK_PENILAIAN_KOREKSI ("TAPUAUK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_ASRUK),
	ASRUK_RENCANA_RUTIN ("KAPUAUK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_ASRUK),
	ASRUK_RENCANA_KOREKSI ("KAPUAUK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_ASRUK),
	ASRUK_REALISASI_RUTIN ("PAPUAUK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_ASRUK),
	ASRUK_REALISASI_KOREKSI ("PAPUAUK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_ASRUK),

	REASK_PENILAIAN_RUTIN ("TAPUARK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_REASK),
	REASK_PENILAIAN_KOREKSI ("TAPUARK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_REASK),
	REASK_RENCANA_RUTIN ("KAPUARK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_REASK),
	REASK_RENCANA_KOREKSI ("KAPUARK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_REASK),
	REASK_REALISASI_RUTIN ("PAPUARK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_REASK),
	REASK_REALISASI_KOREKSI ("PAPUARK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_REASK),

	ASRJS_PENILAIAN_RUTIN ("TAPUAJS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_ASRJS),
	ASRJS_PENILAIAN_KOREKSI ("TAPUAJS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_ASRJS),
	ASRJS_RENCANA_RUTIN ("KAPUAJS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_ASRJS),
	ASRJS_RENCANA_KOREKSI ("KAPUAJS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_ASRJS),
	ASRJS_REALISASI_RUTIN ("PAPUAJS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_ASRJS),
	ASRJS_REALISASI_KOREKSI ("PAPUAJS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_ASRJS),

	ASRUS_PENILAIAN_RUTIN ("TAPUAUS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_ASRUS),
	ASRUS_PENILAIAN_KOREKSI ("TAPUAUS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_ASRUS),
	ASRUS_RENCANA_RUTIN ("KAPUAUS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_ASRUS),
	ASRUS_RENCANA_KOREKSI ("KAPUAUS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_ASRUS),
	ASRUS_REALISASI_RUTIN ("PAPUAUS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_ASRUS),
	ASRUS_REALISASI_KOREKSI ("PAPUAUS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_ASRUS),

	REASS_PENILAIAN_RUTIN ("TAPUARS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_REASS),
	REASS_PENILAIAN_KOREKSI ("TAPUARS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_REASS),
	REASS_RENCANA_RUTIN ("KAPUARS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_REASS),
	REASS_RENCANA_KOREKSI ("KAPUARS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_REASS),
	REASS_REALISASI_RUTIN ("PAPUARS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_REASS),
	REASS_REALISASI_KOREKSI ("PAPUARS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_REASS),

	DPLKK_PENILAIAN_RUTIN ("TAPUDLK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_DPLKK),
	DPLKK_PENILAIAN_KOREKSI ("TAPUDLK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_DPLKK),
	DPLKK_RENCANA_RUTIN ("KAPUDLK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_DPLKK),
	DPLKK_RENCANA_KOREKSI ("KAPUDLK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_DPLKK),
	DPLKK_REALISASI_RUTIN ("PAPUDLK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_DPLKK),
	DPLKK_REALISASI_KOREKSI ("PAPUDLK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_DPLKK),

	DPLKS_PENILAIAN_RUTIN ("TAPUDLS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_DPLKS),
	DPLKS_PENILAIAN_KOREKSI ("TAPUDLS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_DPLKS),
	DPLKS_RENCANA_RUTIN ("KAPUDLS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_DPLKS),
	DPLKS_RENCANA_KOREKSI ("KAPUDLS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_DPLKS),
	DPLKS_REALISASI_RUTIN ("PAPUDLS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_DPLKS),
	DPLKS_REALISASI_KOREKSI ("PAPUDLS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_DPLKS),

	PPK_PENILAIAN_RUTIN ("TAPUPPK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_PPK),
	PPK_PENILAIAN_KOREKSI ("TAPUPPK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_PPK),
	PPK_RENCANA_RUTIN ("KAPUPPK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_PPK),
	PPK_RENCANA_KOREKSI ("KAPUPPK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_PPK),
	PPK_REALISASI_RUTIN ("PAPUPPK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_PPK),
	PPK_REALISASI_KOREKSI ("PAPUPPK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_PPK),

	PPS_PENILAIAN_RUTIN ("TAPUPPS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_PPS),
	PPS_PENILAIAN_KOREKSI ("TAPUPPS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_PPS),
	PPS_RENCANA_RUTIN ("KAPUPPS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_PPS),
	PPS_RENCANA_KOREKSI ("KAPUPPS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_PPS),
	PPS_REALISASI_RUTIN ("PAPUPPS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_PPS),
	PPS_REALISASI_KOREKSI ("PAPUPPS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_PPS),

	PMVK_PENILAIAN_RUTIN ("TAPUPVK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_PMVK),
	PMVK_PENILAIAN_KOREKSI ("TAPUPVK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_PMVK),
	PMVK_RENCANA_RUTIN ("KAPUPVK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_PMVK),
	PMVK_RENCANA_KOREKSI ("KAPUPVK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_PMVK),
	PMVK_REALISASI_RUTIN ("PAPUPVK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_PMVK),
	PMVK_REALISASI_KOREKSI ("PAPUPVK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_PMVK),

	PMVS_PENILAIAN_RUTIN ("TAPUPVS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_PMVS),
	PMVS_PENILAIAN_KOREKSI ("TAPUPVS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_PMVS),
	PMVS_RENCANA_RUTIN ("KAPUPVS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_PMVS),
	PMVS_RENCANA_KOREKSI ("KAPUPVS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_PMVS),
	PMVS_REALISASI_RUTIN ("PAPUPVS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_PMVS),
	PMVS_REALISASI_KOREKSI ("PAPUPVS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_PMVS),

	GDK_PENILAIAN_RUTIN ("TAPUGDK", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_GDK),
	GDK_PENILAIAN_KOREKSI ("TAPUGDK", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_GDK),
	GDK_RENCANA_RUTIN ("KAPUGDK", EReportGroupApu.RENCANA_RUTIN, EReport.APU_GDK),
	GDK_RENCANA_KOREKSI ("KAPUGDK", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_GDK),
	GDK_REALISASI_RUTIN ("PAPUGDK", EReportGroupApu.REALISASI_RUTIN, EReport.APU_GDK),
	GDK_REALISASI_KOREKSI ("PAPUGDK", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_GDK),

	GDS_PENILAIAN_RUTIN ("TAPUGDS", EReportGroupApu.PENILAIAN_RUTIN, EReport.APU_GDS),
	GDS_PENILAIAN_KOREKSI ("TAPUGDS", EReportGroupApu.PENILAIAN_KOREKSI, EReport.APU_GDS),
	GDS_RENCANA_RUTIN ("KAPUGDS", EReportGroupApu.RENCANA_RUTIN, EReport.APU_GDS),
	GDS_RENCANA_KOREKSI ("KAPUGDS", EReportGroupApu.RENCANA_KOREKSI, EReport.APU_GDS),
	GDS_REALISASI_RUTIN ("PAPUGDS", EReportGroupApu.REALISASI_RUTIN, EReport.APU_GDS),
	GDS_REALISASI_KOREKSI ("PAPUGDS", EReportGroupApu.REALISASI_KOREKSI, EReport.APU_GDS),

	FINK_PENILAIAN_RUTIN ("TAPUFNK", EReportGroupApu.PENILAIAN_RUTIN_2, EReport.APU_FINK),
	FINK_PENILAIAN_KOREKSI ("TAPUFNK", EReportGroupApu.PENILAIAN_KOREKSI_2, EReport.APU_FINK),
	FINK_PENILAIAN_PERBAIKAN ("TAPUFNK", EReportGroupApu.PENILAIAN_PERBAIKAN, EReport.APU_FINK),

	FINS_PENILAIAN_RUTIN ("TAPUFNS", EReportGroupApu.PENILAIAN_RUTIN_2, EReport.APU_FINS),
	FINS_PENILAIAN_KOREKSI ("TAPUFNS", EReportGroupApu.PENILAIAN_KOREKSI_2, EReport.APU_FINS),
	FINS_PENILAIAN_PERBAIKAN ("TAPUFNS", EReportGroupApu.PENILAIAN_PERBAIKAN, EReport.APU_FINS),
	;
	
	private String reportTypeCode;
	private EReportGroupApu reportGroup;
	private EReport report;
	
	private EReportApu(String reportTypeCode, EReportGroupApu reportGroup, EReport report) {
		this.reportTypeCode = reportTypeCode;
		this.reportGroup = reportGroup;
		this.report = report;
	}
	
	public String getReportTypeCode() {
		return reportTypeCode;
	}
	
	public EReportGroupApu getReportGroup() {
		return reportGroup;
	}
	
	public EReport getReport() {
		return report;
	}
	
	public static ReportInfo getReportInfo(String reportCode, int reportMenuCode) {
		ReportInfo res = new ReportInfo();
		for (EReportApu eEnum : EReportApu.values()) {
			EReport eReport = eEnum.getReport();
			if (eReport.getCode().equals(reportCode) && eEnum.reportGroup.getMenuCode() == reportMenuCode) {
				res.setId(eEnum.name());
				res.setReport(eReport);
				res.setReportGroup(eEnum.reportGroup.getObject());
				res.setReportTypeCode(eEnum.getReportTypeCode());
				break;
			}
		}
		return res;
	}
}
