#OJKClient
#Fri Sep 27 16:40:25 ICT 2024
splitFileSize=50
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\proses
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\selesai
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\master-data\\hasil
proxyPort=8080
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\sumber
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJK\\error-validasi-server\\hasil
