#OJKClient
#Fri Sep 20 14:16:11 ICT 2024
splitFileSize=50
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\proses
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\selesai
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\master-data\\hasil
proxyPort=8080
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\sumber
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PNJS\\error-validasi-server\\hasil
