package id.go.ojk.dppkk.client.builder.field.ltlb.metadata;

import id.go.ojk.client.model.config.SubmissionFormat;
import id.go.ojk.dppkk.client.builder.constant.JenisProgram;
import id.go.ojk.metadata.module.lblt.dppk.field.*;
import id.go.ojk.metadata.util.constants.ProgramType;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.Arrays;
import java.util.List;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class MetadataPPMPK {

    @Getter
    private static final List<SubmissionFormat> metadata = getFormMetadata();

    private static List<SubmissionFormat> getFormMetadata() {
        String REPORT_CODE = JenisProgram.PPMPK.toString();

//        return Arrays.asList(
//                Dppk0000Dtum.formMetadata(REPORT_CODE),
////                new Ltlb0001DTUM(REPORT_CODE).get(),
////                new Ltlb0002LAN(REPORT_CODE).get(),
////                new Ltlb0003LPAN(REPORT_CODE).get(),
////                new Ltlb0004NRC(REPORT_CODE).get(),
////                new Ltlb0005LPHU(REPORT_CODE).get(),
////                new Ltlb0006LAK(REPORT_CODE).get(),
////                new Ltlb0007PST(REPORT_CODE).get(),
////                new Ltlb0008KUP(REPORT_CODE).get(),
////                new Ltlb0009REKINV(REPORT_CODE).get(),
////                new Ltlb0010ROI(REPORT_CODE).get(),
////                new Ltlb0011ROIML(REPORT_CODE).get(),
////                new Ltlb0012ROISM(REPORT_CODE).get(),
////                new Ltlb0013ALM(REPORT_CODE).get(),
////                new Ltlb0014INSP(REPORT_CODE).get(),
////                new Ltlb0015INPT(REPORT_CODE).get(),
////                new Ltlb0016INBM(REPORT_CODE).get(),
////                new Ltlb0017SBN(REPORT_CODE).get(),
////                new Ltlb0018RAS1(REPORT_CODE).get(),
////                new Ltlb0019RAS2(REPORT_CODE).get(),
////                new Ltlb0020PIUS(REPORT_CODE).get(),
////                new Ltlb0021PMI(REPORT_CODE).get(),
////                new Ltlb0022TBDSP(REPORT_CODE).get(),
////                new Ltlb0023DOC(REPORT_CODE).get(),
////                new Ltlb0024DPJKA(REPORT_CODE).get(),
////                new Ltlb0025DPJKV(REPORT_CODE).get(),
////                new Ltlb0026SRDP(REPORT_CODE).get(),
////                new Ltlb0027SBI(REPORT_CODE).get(),
////                new Ltlb0028RSBN(REPORT_CODE).get(),
////                new Ltlb0029SHM(REPORT_CODE).get(),
////                new Ltlb0030OBLI(REPORT_CODE).get(),
////                new Ltlb0031SUKUK(REPORT_CODE).get(),
////                new Ltlb0032OBSUD(REPORT_CODE).get(),
////                new Ltlb0033RKSD(REPORT_CODE).get(),
//                new Ltlb0034MTN(REPORT_CODE).get(),
//                new Ltlb0035EBA(REPORT_CODE).get(),
//                new Ltlb0036DIRE(REPORT_CODE).get(),
////                new Ltlb0037DNFRA(REPORT_CODE).get(),
////                new Ltlb0038KOKB(REPORT_CODE).get(),
////                new Ltlb0039REPO(REPORT_CODE).get(),
////                new Ltlb0040PNYL(REPORT_CODE).get(),
////                new Ltlb0041PROP(REPORT_CODE).get(),
////                new Ltlb0042KASB(REPORT_CODE).get(),
////                new Ltlb0043PIUT(REPORT_CODE).get(),
////                new Ltlb0044PIUB(REPORT_CODE).get(),
////                new Ltlb0045BBMK(REPORT_CODE).get(),
////                new Ltlb0046PIUI(REPORT_CODE).get(),
////                new Ltlb0047PIHI(REPORT_CODE).get(),
////                new Ltlb0048PILL(REPORT_CODE).get(),
////                new Ltlb0049TNBG(REPORT_CODE).get(),
////                new Ltlb0050KNDR(REPORT_CODE).get(),
////                new Ltlb0051PKOM(REPORT_CODE).get(),
////                new Ltlb0052PKAN(REPORT_CODE).get(),
////                new Ltlb0053ASOL(REPORT_CODE).get(),
////                new Ltlb0054ASLN(REPORT_CODE).get(),
////                new Ltlb0055UMPJ(REPORT_CODE).get(),
////                new Ltlb0056UMPS(REPORT_CODE).get(),
////                new Ltlb0057UTIN(REPORT_CODE).get(),
////                new Ltlb0058PDDM(REPORT_CODE).get(),
////                new Ltlb0059BMHB(REPORT_CODE).get(),
////                new Ltlb0060UTLN(REPORT_CODE).get(),
////                new Ltlb0061PPIN(REPORT_CODE).get(),
////                new Ltlb0062IUR(REPORT_CODE).get(),
////                new Ltlb0063PDIN(REPORT_CODE).get(),
////                new Ltlb0064PDPL(REPORT_CODE).get(),
////                new Ltlb0065BINV(REPORT_CODE).get(),
////                new Ltlb0066BOPR(REPORT_CODE).get(),
////                new Ltlb0067BIPR(REPORT_CODE).get(),
////                new Ltlb0068PPH(REPORT_CODE).get(),
////                new Ltlb0069PKPL(REPORT_CODE).get(),
//                Dppk0069Cover.getFormMetadata(REPORT_CODE)
//                );

        ProgramType programType = ProgramType.PPMPK;

        return Arrays.asList(
                Dppk0000Dtum.formMetadata(programType),
                Dppk0001Lan.formMetadata(programType),
                Dppk0002Lpan.formMetadata(programType),
                Dppk0003Nrc.formMetadata(programType),
                Dppk0004Lphu.formMetadata(programType),
                Dppk0005Lak.formMetadata(programType),
                Dppk0006Pst.formMetadata(programType),
                Dppk0007Kup.formMetadata(programType),
                Dppk0008Rekinv.formMetadata(programType),
                Dppk0009Roi.formMetadata(programType),
                Dppk0010Roiml.formMetadata(programType),
                Dppk0011Roism.formMetadata(programType),
                Dppk0012Alm.formMetadata(programType),
                Dppk0013Insp.formMetadata(programType),
                Dppk0014Inpt.formMetadata(programType),
                Dppk0015Inbm.formMetadata(programType),
                Dppk0016Sbn.formMetadata(programType),
                Dppk0017Ras1.formMetadata(programType),
                Dppk0018Ras2.formMetadata(programType),
                Dppk0019Pius.formMetadata(programType),
                Dppk0020Pmi.formMetadata(programType),
                Dppk0021Tbdsp.formMetadata(programType),
                Dppk0022Doc.formMetadata(programType),
                Dppk0023Dpjka.formMetadata(programType),
                Dppk0024Dpjkv.formMetadata(programType),
                Dppk0025Srdp.formMetadata(programType),
                Dppk0026Sbi.formMetadata(programType),
                Dppk0027Rsbn.formMetadata(programType),
                Dppk0028Shm.formMetadata(programType),
                Dppk0029Obli.formMetadata(programType),
                Dppk0030Sukuk.formMetadata(programType),
                Dppk0031Obsud.formMetadata(programType),
                Dppk0032Rksd.formMetadata(programType),
                Dppk0033Mtn.formMetadata(programType),
                Dppk0034Eba.formMetadata(programType),
                Dppk0035Dire.formMetadata(programType),
                Dppk0036Dnfra.formMetadata(programType),
                Dppk0037Kokb.formMetadata(programType),
                Dppk0038Repo.formMetadata(programType),
                Dppk0039Pnyl.formMetadata(programType),
                Dppk0040Prop.formMetadata(programType),
                Dppk0041Kasb.formMetadata(programType),
                Dppk0042Piut.formMetadata(programType),
                Dppk0043Piub.formMetadata(programType),
                Dppk0044Bbmk.formMetadata(programType),
                Dppk0045Piui.formMetadata(programType),
                Dppk0046Pihi.formMetadata(programType),
                Dppk0047Pill.formMetadata(programType),
                Dppk0048Tnbg.formMetadata(programType),
                Dppk0049Kndr.formMetadata(programType),
                Dppk0050Pkom.formMetadata(programType),
                Dppk0051Pkan.formMetadata(programType),
                Dppk0052Asol.formMetadata(programType),
                Dppk0053Asln.formMetadata(programType),
                Dppk0054Umpj.formMetadata(programType),
                Dppk0055Umps.formMetadata(programType),
                Dppk0056Utin.formMetadata(programType),
                Dppk0057Pddm.formMetadata(programType),
                Dppk0058Bmhb.formMetadata(programType),
                Dppk0059Utln.formMetadata(programType),
                Dppk0060Ppin.formMetadata(programType),
                Dppk0061Iur.formMetadata(programType),
                Dppk0062Pdin.formMetadata(programType),
                Dppk0063Pdpl.formMetadata(programType),
                Dppk0064Binv.formMetadata(programType),
                Dppk0065Bopr.formMetadata(programType),
                Dppk0066Bipr.formMetadata(programType),
                Dppk0067Pph.formMetadata(programType),
                Dppk0068Pkpl.formMetadata(programType),
                Dppk0099Cover.getFormMetadata(programType)
        );
    }
}
