package id.go.ojk.dppkk.client.builder.field.ltlb.metadata;

import id.go.ojk.client.model.config.SubmissionFormat;
import id.go.ojk.dppkk.client.builder.constant.JenisProgram;
import id.go.ojk.module.lblt.dppk.field.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.Arrays;
import java.util.List;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class MetadataPPMPK {

    @Getter
    private static final List<SubmissionFormat> metadata = getFormMetadata();

    private static List<SubmissionFormat> getFormMetadata() {
        String REPORT_CODE = JenisProgram.PPMPK.toString();
//        return Arrays.asList(
//                Dppk0000Dtum.ppmpkKonvensionalFormMetadata(REPORT_CODE),
////                new Ltlb0001DTUM(REPORT_CODE).get(),
////                new Ltlb0002LAN(REPORT_CODE).get(),
////                new Ltlb0003LPAN(REPORT_CODE).get(),
////                new Ltlb0004NRC(REPORT_CODE).get(),
////                new Ltlb0005LPHU(REPORT_CODE).get(),
////                new Ltlb0006LAK(REPORT_CODE).get(),
////                new Ltlb0007PST(REPORT_CODE).get(),
////                new Ltlb0008KUP(REPORT_CODE).get(),
////                new Ltlb0009REKINV(REPORT_CODE).get(),
////                new Ltlb0010ROI(REPORT_CODE).get(),
////                new Ltlb0011ROIML(REPORT_CODE).get(),
////                new Ltlb0012ROISM(REPORT_CODE).get(),
////                new Ltlb0013ALM(REPORT_CODE).get(),
////                new Ltlb0014INSP(REPORT_CODE).get(),
////                new Ltlb0015INPT(REPORT_CODE).get(),
////                new Ltlb0016INBM(REPORT_CODE).get(),
////                new Ltlb0017SBN(REPORT_CODE).get(),
////                new Ltlb0018RAS1(REPORT_CODE).get(),
////                new Ltlb0019RAS2(REPORT_CODE).get(),
////                new Ltlb0020PIUS(REPORT_CODE).get(),
////                new Ltlb0021PMI(REPORT_CODE).get(),
////                new Ltlb0022TBDSP(REPORT_CODE).get(),
////                new Ltlb0023DOC(REPORT_CODE).get(),
////                new Ltlb0024DPJKA(REPORT_CODE).get(),
////                new Ltlb0025DPJKV(REPORT_CODE).get(),
////                new Ltlb0026SRDP(REPORT_CODE).get(),
////                new Ltlb0027SBI(REPORT_CODE).get(),
////                new Ltlb0028RSBN(REPORT_CODE).get(),
////                new Ltlb0029SHM(REPORT_CODE).get(),
////                new Ltlb0030OBLI(REPORT_CODE).get(),
////                new Ltlb0031SUKUK(REPORT_CODE).get(),
////                new Ltlb0032OBSUD(REPORT_CODE).get(),
////                new Ltlb0033RKSD(REPORT_CODE).get(),
//                new Ltlb0034MTN(REPORT_CODE).get(),
//                new Ltlb0035EBA(REPORT_CODE).get(),
//                new Ltlb0036DIRE(REPORT_CODE).get(),
////                new Ltlb0037DNFRA(REPORT_CODE).get(),
////                new Ltlb0038KOKB(REPORT_CODE).get(),
////                new Ltlb0039REPO(REPORT_CODE).get(),
////                new Ltlb0040PNYL(REPORT_CODE).get(),
////                new Ltlb0041PROP(REPORT_CODE).get(),
////                new Ltlb0042KASB(REPORT_CODE).get(),
////                new Ltlb0043PIUT(REPORT_CODE).get(),
////                new Ltlb0044PIUB(REPORT_CODE).get(),
////                new Ltlb0045BBMK(REPORT_CODE).get(),
////                new Ltlb0046PIUI(REPORT_CODE).get(),
////                new Ltlb0047PIHI(REPORT_CODE).get(),
////                new Ltlb0048PILL(REPORT_CODE).get(),
////                new Ltlb0049TNBG(REPORT_CODE).get(),
////                new Ltlb0050KNDR(REPORT_CODE).get(),
////                new Ltlb0051PKOM(REPORT_CODE).get(),
////                new Ltlb0052PKAN(REPORT_CODE).get(),
////                new Ltlb0053ASOL(REPORT_CODE).get(),
////                new Ltlb0054ASLN(REPORT_CODE).get(),
////                new Ltlb0055UMPJ(REPORT_CODE).get(),
////                new Ltlb0056UMPS(REPORT_CODE).get(),
////                new Ltlb0057UTIN(REPORT_CODE).get(),
////                new Ltlb0058PDDM(REPORT_CODE).get(),
////                new Ltlb0059BMHB(REPORT_CODE).get(),
////                new Ltlb0060UTLN(REPORT_CODE).get(),
////                new Ltlb0061PPIN(REPORT_CODE).get(),
////                new Ltlb0062IUR(REPORT_CODE).get(),
////                new Ltlb0063PDIN(REPORT_CODE).get(),
////                new Ltlb0064PDPL(REPORT_CODE).get(),
////                new Ltlb0065BINV(REPORT_CODE).get(),
////                new Ltlb0066BOPR(REPORT_CODE).get(),
////                new Ltlb0067BIPR(REPORT_CODE).get(),
////                new Ltlb0068PPH(REPORT_CODE).get(),
////                new Ltlb0069PKPL(REPORT_CODE).get(),
//                Dppk0069Cover.getFormMetadata(REPORT_CODE)
//                );

        return Arrays.asList(
                Dppk0000Dtum.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0001Lan.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0002Lpan.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0003Nrc.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0004Lphu.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0005Lak.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0006Pst.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0007Kup.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0008Rekinv.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0009Roi.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0010Roiml.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0011Roism.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0012Alm.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0013Insp.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0014Inpt.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0015Inbm.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0016Sbn.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0017Ras1.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0018Ras2.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0019Pius.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0020Pmi.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0021Tbdsp.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0022Doc.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0023Dpjka.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0024Dpjkv.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0025Srdp.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0026Sbi.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0027Rsbn.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0028Shm.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0029Obli.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0030Sukuk.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0031Obsud.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0032Rksd.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0033Mtn.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0034Eba.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0035Dire.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0036Dnfra.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0037Kokb.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0038Repo.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0039Pnyl.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0040Prop.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0041Kasb.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0042Piut.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0043Piub.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0044Bbmk.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0045Piui.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0046Pihi.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0047Pill.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0048Tnbg.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0049Kndr.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0050Pkom.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0051Pkan.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0052Asol.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0053Asln.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0054Umpj.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0055Umps.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0056Utin.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0057Pddm.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0058Bmhb.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0059Utln.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0060Ppin.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0061Iur.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0062Pdin.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0063Pdpl.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0064Binv.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0065Bopr.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0066Bipr.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0067Pph.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0068Pkpl.ppmpkKonvensionalFormMetadata(REPORT_CODE),
                Dppk0099Cover.getFormMetadata(REPORT_CODE)
        );
    }
}
