package id.go.ojk.dppkk.client.builder.field.ltlb.metadata;

import id.go.ojk.client.model.config.SubmissionFormat;
import id.go.ojk.dppkk.client.builder.constant.JenisProgram;
import id.go.ojk.module.lblt.dppk.field.*;
import id.go.ojk.util.constants.ProgramType;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.Arrays;
import java.util.List;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class MetadataPPMPK {

    @Getter
    private static final List<SubmissionFormat> metadata = getFormMetadata();

    private static List<SubmissionFormat> getFormMetadata() {
        String REPORT_CODE = JenisProgram.PPMPK.toString();

//        return Arrays.asList(
//                Dppk0000Dtum.ppmpKonvensionalFormMetadata(REPORT_CODE),
////                new Ltlb0001DTUM(REPORT_CODE).get(),
////                new Ltlb0002LAN(REPORT_CODE).get(),
////                new Ltlb0003LPAN(REPORT_CODE).get(),
////                new Ltlb0004NRC(REPORT_CODE).get(),
////                new Ltlb0005LPHU(REPORT_CODE).get(),
////                new Ltlb0006LAK(REPORT_CODE).get(),
////                new Ltlb0007PST(REPORT_CODE).get(),
////                new Ltlb0008KUP(REPORT_CODE).get(),
////                new Ltlb0009REKINV(REPORT_CODE).get(),
////                new Ltlb0010ROI(REPORT_CODE).get(),
////                new Ltlb0011ROIML(REPORT_CODE).get(),
////                new Ltlb0012ROISM(REPORT_CODE).get(),
////                new Ltlb0013ALM(REPORT_CODE).get(),
////                new Ltlb0014INSP(REPORT_CODE).get(),
////                new Ltlb0015INPT(REPORT_CODE).get(),
////                new Ltlb0016INBM(REPORT_CODE).get(),
////                new Ltlb0017SBN(REPORT_CODE).get(),
////                new Ltlb0018RAS1(REPORT_CODE).get(),
////                new Ltlb0019RAS2(REPORT_CODE).get(),
////                new Ltlb0020PIUS(REPORT_CODE).get(),
////                new Ltlb0021PMI(REPORT_CODE).get(),
////                new Ltlb0022TBDSP(REPORT_CODE).get(),
////                new Ltlb0023DOC(REPORT_CODE).get(),
////                new Ltlb0024DPJKA(REPORT_CODE).get(),
////                new Ltlb0025DPJKV(REPORT_CODE).get(),
////                new Ltlb0026SRDP(REPORT_CODE).get(),
////                new Ltlb0027SBI(REPORT_CODE).get(),
////                new Ltlb0028RSBN(REPORT_CODE).get(),
////                new Ltlb0029SHM(REPORT_CODE).get(),
////                new Ltlb0030OBLI(REPORT_CODE).get(),
////                new Ltlb0031SUKUK(REPORT_CODE).get(),
////                new Ltlb0032OBSUD(REPORT_CODE).get(),
////                new Ltlb0033RKSD(REPORT_CODE).get(),
//                new Ltlb0034MTN(REPORT_CODE).get(),
//                new Ltlb0035EBA(REPORT_CODE).get(),
//                new Ltlb0036DIRE(REPORT_CODE).get(),
////                new Ltlb0037DNFRA(REPORT_CODE).get(),
////                new Ltlb0038KOKB(REPORT_CODE).get(),
////                new Ltlb0039REPO(REPORT_CODE).get(),
////                new Ltlb0040PNYL(REPORT_CODE).get(),
////                new Ltlb0041PROP(REPORT_CODE).get(),
////                new Ltlb0042KASB(REPORT_CODE).get(),
////                new Ltlb0043PIUT(REPORT_CODE).get(),
////                new Ltlb0044PIUB(REPORT_CODE).get(),
////                new Ltlb0045BBMK(REPORT_CODE).get(),
////                new Ltlb0046PIUI(REPORT_CODE).get(),
////                new Ltlb0047PIHI(REPORT_CODE).get(),
////                new Ltlb0048PILL(REPORT_CODE).get(),
////                new Ltlb0049TNBG(REPORT_CODE).get(),
////                new Ltlb0050KNDR(REPORT_CODE).get(),
////                new Ltlb0051PKOM(REPORT_CODE).get(),
////                new Ltlb0052PKAN(REPORT_CODE).get(),
////                new Ltlb0053ASOL(REPORT_CODE).get(),
////                new Ltlb0054ASLN(REPORT_CODE).get(),
////                new Ltlb0055UMPJ(REPORT_CODE).get(),
////                new Ltlb0056UMPS(REPORT_CODE).get(),
////                new Ltlb0057UTIN(REPORT_CODE).get(),
////                new Ltlb0058PDDM(REPORT_CODE).get(),
////                new Ltlb0059BMHB(REPORT_CODE).get(),
////                new Ltlb0060UTLN(REPORT_CODE).get(),
////                new Ltlb0061PPIN(REPORT_CODE).get(),
////                new Ltlb0062IUR(REPORT_CODE).get(),
////                new Ltlb0063PDIN(REPORT_CODE).get(),
////                new Ltlb0064PDPL(REPORT_CODE).get(),
////                new Ltlb0065BINV(REPORT_CODE).get(),
////                new Ltlb0066BOPR(REPORT_CODE).get(),
////                new Ltlb0067BIPR(REPORT_CODE).get(),
////                new Ltlb0068PPH(REPORT_CODE).get(),
////                new Ltlb0069PKPL(REPORT_CODE).get(),
//                Dppk0069Cover.getFormMetadata(REPORT_CODE)
//                );

        ProgramType programType = ProgramType.PPMPK;

        return Arrays.asList(
                Dppk0000Dtum.ppmpKonvensionalFormMetadata(programType),
                Dppk0001Lan.ppmpKonvensionalFormMetadata(programType),
                Dppk0002Lpan.ppmpKonvensionalFormMetadata(programType),
                Dppk0003Nrc.ppmpKonvensionalFormMetadata(programType),
                Dppk0004Lphu.ppmpKonvensionalFormMetadata(programType),
                Dppk0005Lak.ppmpKonvensionalFormMetadata(programType),
                Dppk0006Pst.ppmpKonvensionalFormMetadata(programType),
                Dppk0007Kup.ppmpKonvensionalFormMetadata(programType),
                Dppk0008Rekinv.ppmpKonvensionalFormMetadata(programType),
                Dppk0009Roi.ppmpKonvensionalFormMetadata(programType),
                Dppk0010Roiml.ppmpKonvensionalFormMetadata(programType),
                Dppk0011Roism.ppmpKonvensionalFormMetadata(programType),
                Dppk0012Alm.ppmpKonvensionalFormMetadata(programType),
                Dppk0013Insp.ppmpKonvensionalFormMetadata(programType),
                Dppk0014Inpt.ppmpKonvensionalFormMetadata(programType),
                Dppk0015Inbm.ppmpKonvensionalFormMetadata(programType),
                Dppk0016Sbn.ppmpKonvensionalFormMetadata(programType),
                Dppk0017Ras1.ppmpKonvensionalFormMetadata(programType),
                Dppk0018Ras2.ppmpKonvensionalFormMetadata(programType),
                Dppk0019Pius.ppmpKonvensionalFormMetadata(programType),
                Dppk0020Pmi.ppmpKonvensionalFormMetadata(programType),
                Dppk0021Tbdsp.ppmpKonvensionalFormMetadata(programType),
                Dppk0022Doc.ppmpKonvensionalFormMetadata(programType),
                Dppk0023Dpjka.ppmpKonvensionalFormMetadata(programType),
                Dppk0024Dpjkv.ppmpKonvensionalFormMetadata(programType),
                Dppk0025Srdp.ppmpKonvensionalFormMetadata(programType),
                Dppk0026Sbi.ppmpKonvensionalFormMetadata(programType),
                Dppk0027Rsbn.ppmpKonvensionalFormMetadata(programType),
                Dppk0028Shm.ppmpKonvensionalFormMetadata(programType),
                Dppk0029Obli.ppmpKonvensionalFormMetadata(programType),
                Dppk0030Sukuk.ppmpKonvensionalFormMetadata(programType),
                Dppk0031Obsud.ppmpKonvensionalFormMetadata(programType),
                Dppk0032Rksd.ppmpKonvensionalFormMetadata(programType),
                Dppk0033Mtn.ppmpKonvensionalFormMetadata(programType),
                Dppk0034Eba.ppmpKonvensionalFormMetadata(programType),
                Dppk0035Dire.ppmpKonvensionalFormMetadata(programType),
                Dppk0036Dnfra.ppmpKonvensionalFormMetadata(programType),
                Dppk0037Kokb.ppmpKonvensionalFormMetadata(programType),
                Dppk0038Repo.ppmpKonvensionalFormMetadata(programType),
                Dppk0039Pnyl.ppmpKonvensionalFormMetadata(programType),
                Dppk0040Prop.ppmpKonvensionalFormMetadata(programType),
                Dppk0041Kasb.ppmpKonvensionalFormMetadata(programType),
                Dppk0042Piut.ppmpKonvensionalFormMetadata(programType),
                Dppk0043Piub.ppmpKonvensionalFormMetadata(programType),
                Dppk0044Bbmk.ppmpKonvensionalFormMetadata(programType),
                Dppk0045Piui.ppmpKonvensionalFormMetadata(programType),
                Dppk0046Pihi.ppmpKonvensionalFormMetadata(programType),
                Dppk0047Pill.ppmpKonvensionalFormMetadata(programType),
                Dppk0048Tnbg.ppmpKonvensionalFormMetadata(programType),
                Dppk0049Kndr.ppmpKonvensionalFormMetadata(programType),
                Dppk0050Pkom.ppmpKonvensionalFormMetadata(programType),
                Dppk0051Pkan.ppmpKonvensionalFormMetadata(programType),
                Dppk0052Asol.ppmpKonvensionalFormMetadata(programType),
                Dppk0053Asln.ppmpKonvensionalFormMetadata(programType),
                Dppk0054Umpj.ppmpKonvensionalFormMetadata(programType),
                Dppk0055Umps.ppmpKonvensionalFormMetadata(programType),
                Dppk0056Utin.ppmpKonvensionalFormMetadata(programType),
                Dppk0057Pddm.ppmpKonvensionalFormMetadata(programType),
                Dppk0058Bmhb.ppmpKonvensionalFormMetadata(programType),
                Dppk0059Utln.ppmpKonvensionalFormMetadata(programType),
                Dppk0060Ppin.ppmpKonvensionalFormMetadata(programType),
                Dppk0061Iur.ppmpKonvensionalFormMetadata(programType),
                Dppk0062Pdin.ppmpKonvensionalFormMetadata(programType),
                Dppk0063Pdpl.ppmpKonvensionalFormMetadata(programType),
                Dppk0064Binv.ppmpKonvensionalFormMetadata(programType),
                Dppk0065Bopr.ppmpKonvensionalFormMetadata(programType),
                Dppk0066Bipr.ppmpKonvensionalFormMetadata(programType),
                Dppk0067Pph.ppmpKonvensionalFormMetadata(programType),
                Dppk0068Pkpl.ppmpKonvensionalFormMetadata(programType),
                Dppk0099Cover.getFormMetadata(programType)
        );
    }
}
