package id.go.ojk.pnmk.client.builder.field;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum EFormLaporanBulanan {
	LB_0000 ("0000", "PROFIL PERUSAHAAN"),
	LB_0020 ("0020", "RINCIAN KANTOR SELAIN KANTOR PUSAT"),
	LB_0030 ("0030", "RINCIAN JUMLAH PEGAWAI "),
	LB_1100 ("1100", "LAPORAN POSISI KEUANGAN"),
	LB_1200 ("1200", "LAPORAN LABA RUGI DAN PENGHASILAN KOMPREHENSIF LAIN"),
	LB_1300 ("1300", "LAPORAN ARUS KAS"),
	LB_1400 ("1400", "LAPORAN ANALISIS KESESUAIAN ASET DAN LIABILITAS "),
	LB_2100 ("2100", "RINCIAN KAS DAN SETARA KAS"),
	LB_2200 ("2200", "RINCIAN PENEMPATAN PADA BANK"),
	LB_2300 ("2300", "RINCIAN SURAT BERHARGA YANG DIMILIKI"),
	LB_2400 ("2400", "RINCIAN PEMBIAYAAN DAN PIUTANG/KREDIT YANG DIBERIKAN ULaMM/ULaMM SYARIAH"),
	LB_2500 ("2500", "RINCIAN PEMBIAYAAN DAN PIUTANG/KREDIT YANG DIBERIKAN MEKAAR/MEKAAR SYARIAH"),
	LB_2600 ("2600", "RINCIAN SURAT BERHARGA YANG DITERBITKAN"),
	LB_2700 ("2700", "RINCIAN PINJAMAN YANG DITERIMA"),
	LB_2800 ("2800", "RINCIAN CADANGAN KERUGIAN PENURUNAN NILAI (CKPN) ASET KEUANGAN"),
	;
	
	@Getter
	private String code;
	@Getter
	private String name;
}
