#OJKClient
#Thu Oct 23 11:34:36 ICT 2025
splitFileSize=20
errorDataSourceDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\proses
updateOfflineFileDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\resources\\data.dat
submissionDoneDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\selesai
sendindSourceDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\selesai
summarySourceDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\master-data\\hasil
readTimeout=60000,90000,120000
proxyPort=8080
submissionSourceDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\sumber
connectTimeout=3000
masterDataSourceDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=Z\:\\Work\\Apolo PM\\Code\\IKNBClient\\OJK-PA\\error-validasi-server\\hasil
