#OJKClient
#Wed Jan 14 07:21:42 ICT 2026
splitFileSize=20
errorDataSourceDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\proses
updateOfflineFileDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\resources\\data.dat
submissionDoneDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\selesai
sendindSourceDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\selesai
summarySourceDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\master-data\\hasil
readTimeout=60000,90000,120000
proxyPort=8080
submissionSourceDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
connectTimeout=3000
masterDataSourceDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=D\:\\Projects\\OJK\\IKNB\\DAPEN\\source\\IKNB-DAPEN\\OJK-BPKS\\OJK-BPKS-Client-Builder\\error-validasi-server\\hasil
