#OJKClient
#Sun Jul 31 13:57:24 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-PMVK\\error-validasi-server\\hasil
proxyPort=8080
