#OJKClient
#Sun May 29 21:19:57 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRUS\\error-validasi-server\\hasil
proxyPort=8080
