#OJKClient
#Mon Feb 19 19:27:45 ICT 2024
splitFileSize=50
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\proses
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\selesai
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\master-data\\hasil
proxyPort=8080
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\sumber
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\OJK-ASRJK-Client-Builder\\error-validasi-server\\hasil
