#OJKClient
#Thu Jul 17 07:20:15 ICT 2025
splitFileSize=20
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\proses
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\selesai
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\master-data\\hasil
readTimeout=60000,90000,120000
proxyPort=8080
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\sumber
connectTimeout=3000
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\IKNBClient-v3\\OJK-LKK\\error-validasi-server\\hasil
