#Client
#Mon Dec 01 17:26:54 ICT 2025
splitFileSize=20
errorDataSourceDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
submissionProcessDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\proses
maxErrorCount=500
updateOfflineFileDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\resources\\data.dat
submissionDoneDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\selesai
sendindSourceDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\selesai
summarySourceDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\master-data\\hasil
proxyPort=8080
submissionSourceDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber\\5c\\Bulanan 2025-06-30 R
readTimeout=60000,90000,120000
masterDataSourceDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\Pelaporan\\sumber
connectTimeout=3000
connectionType=internet
proxyHost=
errorDataDoneDir=D\:\\Projects\\OJK\\IKNB\\2024\\Source\\IKNBClient\\OJK-BPKS\\OJK-BPKS-Client-Builder\\error-validasi-server\\hasil
