#OJKClient
#Wed Sep 27 07:58:32 ICT 2023
splitFileSize=20
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\sumber
validationLoopDelay=300
maxThread=0
proxyUser=
maxErrorCount=500
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\proses
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\selesai
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\sumber
proxyPassword=
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\master-data\\hasil
proxyPort=8080
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\sumber
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\Pelaporan\\sumber
proxyHost=
connectionType=internet
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient\\OJK-ASRJK\\error-validasi-server\\hasil
