#OJKClient
#Fri Mar 25 07:57:41 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-PPK\\error-validasi-server\\hasil
proxyPort=8080
