#OJKClient
#Wed Sep 21 08:17:58 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\_other\\ojk\\IKNBClient-1\\OJK-PPIS\\error-validasi-server\\hasil
proxyPort=8080
