package id.go.ojk.reask.client.builder.field;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum EFormSelfAssessmentUus {
	SA_0201 ("0201", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO STRATEGIS"),
	SA_0202 ("0202", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO OPERASIONAL"),
	SA_0203 ("0203", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO ASURANSI"),
	SA_0204 ("0204", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO KREDIT"),
	SA_0205 ("0205", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO PASAR"),
	SA_0206 ("0206", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO LIKUIDITAS"),
	SA_0207 ("0207", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO HUKUM"),
	SA_0208 ("0208", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO KEPATUHAN"),
	SA_0209 ("0209", "PENILAIAN FAKTOR PROFIL RISIKO TINGKAT KESEHATAN PERUSAHAAN ASURANSI DAN PERUSAHAAN REASURANSI - PENILAIAN RISIKO REPUTASI"),
	SA_0210 ("0210", "Analisis Penilaian Risiko dan Peringkat Faktor Profil Risiko"),
	SA_0211 ("0211", "Penetapan Profil Risiko Komposit "),
	SA_8888 ("8888", "SURAT PENGANTAR"),
	SA_9999 ("9999", "LAPORAN SELF ASSESSMENT KUALITATIF"),
	;

	@Getter
	private String code;
	@Getter
	private String name;
}
