#OJKClient
#Fri Mar 25 07:28:54 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-GDS\\error-validasi-server\\hasil
proxyPort=8080
