package id.go.ojk.client.module.rb;

import id.go.ojk.client.constant.EReport;
import id.go.ojk.client.model.ReportInfo;

public enum EReportRb {
	ASRJK_PELAPORAN ("RBASRJK", EReportGroupRb.PELAPORAN, EReport.RB_ASRJK),
	ASRJK_PERUBAHAN ("RBASRJK", EReportGroupRb.PERUBAHAN, EReport.RB_ASRJK),
	ASRJK_PENYESUAIAN ("RBASRJK", EReportGroupRb.PENYESUAIAN, EReport.RB_ASRJK),
	ASRJK_REALISASI ("REASRJK", EReportGroupRb.REALISASI, EReport.RB_ASRJK),
	ASRJK_PENGAWASAN ("RPASRJK", EReportGroupRb.PENGAWASAN, EReport.RB_ASRJK),

	ASRJU_PELAPORAN ("RBASRJUS", EReportGroupRb.PELAPORAN, EReport.RB_ASRJU),
	ASRJU_PERUBAHAN ("RBASRJUS", EReportGroupRb.PERUBAHAN, EReport.RB_ASRJU),
	ASRJU_PENYESUAIAN ("RBASRJUS", EReportGroupRb.PENYESUAIAN, EReport.RB_ASRJU),
	ASRJU_REALISASI ("REASRJUS", EReportGroupRb.REALISASI, EReport.RB_ASRJU),
	ASRJU_PENGAWASAN ("RPASRJUS", EReportGroupRb.PENGAWASAN, EReport.RB_ASRJU),

	ASRUK_PELAPORAN ("RBASRUK", EReportGroupRb.PELAPORAN, EReport.RB_ASRUK),
	ASRUK_PERUBAHAN ("RBASRUK", EReportGroupRb.PERUBAHAN, EReport.RB_ASRUK),
	ASRUK_PENYESUAIAN ("RBASRUK", EReportGroupRb.PENYESUAIAN, EReport.RB_ASRUK),
	ASRUK_REALISASI ("REASRUK", EReportGroupRb.REALISASI, EReport.RB_ASRUK),
	ASRUK_PENGAWASAN ("RPASRUK", EReportGroupRb.PENGAWASAN, EReport.RB_ASRUK),

	ASRUU_PELAPORAN ("RBASRUUS", EReportGroupRb.PELAPORAN, EReport.RB_ASRUU),
	ASRUU_PERUBAHAN ("RBASRUUS", EReportGroupRb.PERUBAHAN, EReport.RB_ASRUU),
	ASRUU_PENYESUAIAN ("RBASRUUS", EReportGroupRb.PENYESUAIAN, EReport.RB_ASRUU),
	ASRUU_REALISASI ("REASRUUS", EReportGroupRb.REALISASI, EReport.RB_ASRUU),
	ASRUU_PENGAWASAN ("RPASRUUS", EReportGroupRb.PENGAWASAN, EReport.RB_ASRUU),
	
	REASK_PELAPORAN ("RBREASK", EReportGroupRb.PELAPORAN, EReport.RB_REASK),
	REASK_PERUBAHAN ("RBREASK", EReportGroupRb.PERUBAHAN, EReport.RB_REASK),
	REASK_PENYESUAIAN ("RBREASK", EReportGroupRb.PENYESUAIAN, EReport.RB_REASK),
	REASK_REALISASI ("REREASK", EReportGroupRb.REALISASI, EReport.RB_REASK),
	REASK_PENGAWASAN ("RPREASK", EReportGroupRb.PENGAWASAN, EReport.RB_REASK),
	
	REASU_PELAPORAN ("RBREASUS", EReportGroupRb.PELAPORAN, EReport.RB_REASU),
	REASU_PERUBAHAN ("RBREASUS", EReportGroupRb.PERUBAHAN, EReport.RB_REASU),
	REASU_PENYESUAIAN ("RBREASUS", EReportGroupRb.PENYESUAIAN, EReport.RB_REASU),
	REASU_REALISASI ("REREASUS", EReportGroupRb.REALISASI, EReport.RB_REASU),
	REASU_PENGAWASAN ("RPREASUS", EReportGroupRb.PENGAWASAN, EReport.RB_REASU),
	
	PPK_PELAPORAN ("RBPPK", EReportGroupRb.PELAPORAN, EReport.RB_PPK),
	PPK_PERUBAHAN ("RBPPK", EReportGroupRb.PERUBAHAN, EReport.RB_PPK),
	PPK_PENYESUAIAN ("RBPPK", EReportGroupRb.PENYESUAIAN, EReport.RB_PPK),
	PPK_REALISASI ("REPPK", EReportGroupRb.REALISASI, EReport.RB_PPK),
	PPK_PENGAWASAN ("RPPPK", EReportGroupRb.PENGAWASAN, EReport.RB_PPK),
	
	DPPKK_PELAPORAN ("RBDPPKK", EReportGroupRb.PELAPORAN, EReport.RB_DPPKK),
	DPPKK_PERUBAHAN ("RBDPPKK", EReportGroupRb.PERUBAHAN, EReport.RB_DPPKK),
	DPPKK_PENYESUAIAN ("RBDPPKK", EReportGroupRb.PENYESUAIAN, EReport.RB_DPPKK),
	DPPKK_REALISASI ("REDPPKK", EReportGroupRb.REALISASI, EReport.RB_DPPKK),
	DPPKK_PENGAWASAN ("RPDPPKK", EReportGroupRb.PENGAWASAN, EReport.RB_DPPKK),
	
	DPPKU_PELAPORAN ("RBDPPKU", EReportGroupRb.PELAPORAN, EReport.RB_DPPKU),
	DPPKU_PERUBAHAN ("RBDPPKU", EReportGroupRb.PERUBAHAN, EReport.RB_DPPKU),
	DPPKU_PENYESUAIAN ("RBDPPKU", EReportGroupRb.PENYESUAIAN, EReport.RB_DPPKU),
	DPPKU_REALISASI ("REDPPKU", EReportGroupRb.REALISASI, EReport.RB_DPPKU),
	DPPKU_PENGAWASAN ("RPDPPKU", EReportGroupRb.PENGAWASAN, EReport.RB_DPPKU),
	
	DPLKK_PELAPORAN ("RBDPLKK", EReportGroupRb.PELAPORAN, EReport.RB_DPLKK),
	DPLKK_PERUBAHAN ("RBDPLKK", EReportGroupRb.PERUBAHAN, EReport.RB_DPLKK),
	DPLKK_PENYESUAIAN ("RBDPLKK", EReportGroupRb.PENYESUAIAN, EReport.RB_DPLKK),
	DPLKK_REALISASI ("REDPLKK", EReportGroupRb.REALISASI, EReport.RB_DPLKK),
	DPLKK_PENGAWASAN ("RPDPLKK", EReportGroupRb.PENGAWASAN, EReport.RB_DPLKK),
	
	PMVK_PELAPORAN ("RBPMVK", EReportGroupRb.PELAPORAN, EReport.RB_PMVK),
	PMVK_PERUBAHAN ("RBPMVK", EReportGroupRb.PERUBAHAN, EReport.RB_PMVK),
	PMVK_PENYESUAIAN ("RBPMVK", EReportGroupRb.PENYESUAIAN, EReport.RB_PMVK),
	PMVK_REALISASI ("REPMVK", EReportGroupRb.REALISASI, EReport.RB_PMVK),
	PMVK_PENGAWASAN ("RPPMVK", EReportGroupRb.PENGAWASAN, EReport.RB_PMVK),
	
	ASRJS_PELAPORAN ("RBASRJS", EReportGroupRb.PELAPORAN, EReport.RB_ASRJS),
	ASRJS_PERUBAHAN ("RBASRJS", EReportGroupRb.PERUBAHAN, EReport.RB_ASRJS),
	ASRJS_PENYESUAIAN ("RBASRJS", EReportGroupRb.PENYESUAIAN, EReport.RB_ASRJS),
	ASRJS_REALISASI ("REASRJS", EReportGroupRb.REALISASI, EReport.RB_ASRJS),
	ASRJS_PENGAWASAN ("RPASRJS", EReportGroupRb.PENGAWASAN, EReport.RB_ASRJS),

	ASRUS_PELAPORAN ("RBASRUS", EReportGroupRb.PELAPORAN, EReport.RB_ASRUS),
	ASRUS_PERUBAHAN ("RBASRUS", EReportGroupRb.PERUBAHAN, EReport.RB_ASRUS),
	ASRUS_PENYESUAIAN ("RBASRUS", EReportGroupRb.PENYESUAIAN, EReport.RB_ASRUS),
	ASRUS_REALISASI ("REASRUS", EReportGroupRb.REALISASI, EReport.RB_ASRUS),
	ASRUS_PENGAWASAN ("RPASRUS", EReportGroupRb.PENGAWASAN, EReport.RB_ASRUS),

	REASS_PELAPORAN ("RBREASS", EReportGroupRb.PELAPORAN, EReport.RB_REASS),
	REASS_PERUBAHAN ("RBREASS", EReportGroupRb.PERUBAHAN, EReport.RB_REASS),
	REASS_PENYESUAIAN ("RBREASS", EReportGroupRb.PENYESUAIAN, EReport.RB_REASS),
	REASS_REALISASI ("REREASS", EReportGroupRb.REALISASI, EReport.RB_REASS),
	REASS_PENGAWASAN ("RPREASS", EReportGroupRb.PENGAWASAN, EReport.RB_REASS),

	PPS_PELAPORAN ("RBPPS", EReportGroupRb.PELAPORAN, EReport.RB_PPS),
	PPS_PERUBAHAN ("RBPPS", EReportGroupRb.PERUBAHAN, EReport.RB_PPS),
	PPS_PENYESUAIAN ("RBPPS", EReportGroupRb.PENYESUAIAN, EReport.RB_PPS),
	PPS_REALISASI ("REPPS", EReportGroupRb.REALISASI, EReport.RB_PPS),
	PPS_PENGAWASAN ("RPPPS", EReportGroupRb.PENGAWASAN, EReport.RB_PPS),

	PPU_PELAPORAN ("RBPPU", EReportGroupRb.PELAPORAN, EReport.RB_PPU),
	PPU_PERUBAHAN ("RBPPU", EReportGroupRb.PERUBAHAN, EReport.RB_PPU),
	PPU_PENYESUAIAN ("RBPPU", EReportGroupRb.PENYESUAIAN, EReport.RB_PPU),
	PPU_REALISASI ("REPPU", EReportGroupRb.REALISASI, EReport.RB_PPU),
	PPU_PENGAWASAN ("RPPPU", EReportGroupRb.PENGAWASAN, EReport.RB_PPU),

	DPPKS_PELAPORAN ("RBDPPKS", EReportGroupRb.PELAPORAN, EReport.RB_DPPKS),
	DPPKS_PERUBAHAN ("RBDPPKS", EReportGroupRb.PERUBAHAN, EReport.RB_DPPKS),
	DPPKS_PENYESUAIAN ("RBDPPKS", EReportGroupRb.PENYESUAIAN, EReport.RB_DPPKS),
	DPPKS_REALISASI ("REDPPKS", EReportGroupRb.REALISASI, EReport.RB_DPPKS),
	DPPKS_PENGAWASAN ("RPDPPKS", EReportGroupRb.PENGAWASAN, EReport.RB_DPPKS),

	DPLKS_PELAPORAN ("RBDPLKS", EReportGroupRb.PELAPORAN, EReport.RB_DPLKS),
	DPLKS_PERUBAHAN ("RBDPLKS", EReportGroupRb.PERUBAHAN, EReport.RB_DPLKS),
	DPLKS_PENYESUAIAN ("RBDPLKS", EReportGroupRb.PENYESUAIAN, EReport.RB_DPLKS),
	DPLKS_REALISASI ("REDPLKS", EReportGroupRb.REALISASI, EReport.RB_DPLKS),
	DPLKS_PENGAWASAN ("RPDPLKS", EReportGroupRb.PENGAWASAN, EReport.RB_DPLKS),

	PMVS_PELAPORAN ("RBPMVS", EReportGroupRb.PELAPORAN, EReport.RB_PMVS),
	PMVS_PERUBAHAN ("RBPMVS", EReportGroupRb.PERUBAHAN, EReport.RB_PMVS),
	PMVS_PENYESUAIAN ("RBPMVS", EReportGroupRb.PENYESUAIAN, EReport.RB_PMVS),
	PMVS_REALISASI ("REPMVS", EReportGroupRb.REALISASI, EReport.RB_PMVS),
	PMVS_PENGAWASAN ("RPPMVS", EReportGroupRb.PENGAWASAN, EReport.RB_PMVS),

	PMVU_PELAPORAN ("RBPMVU", EReportGroupRb.PELAPORAN, EReport.RB_PMVU),
	PMVU_PERUBAHAN ("RBPMVU", EReportGroupRb.PERUBAHAN, EReport.RB_PMVU),
	PMVU_PENYESUAIAN ("RBPMVU", EReportGroupRb.PENYESUAIAN, EReport.RB_PMVU),
	PMVU_REALISASI ("REPMVU", EReportGroupRb.REALISASI, EReport.RB_PMVU),
	PMVU_PENGAWASAN ("RPPMVU", EReportGroupRb.PENGAWASAN, EReport.RB_PMVU),
	;
	
	private String reportTypeCode;
	private EReportGroupRb reportGroup;
	private EReport report;
	
	private EReportRb(String reportTypeCode, EReportGroupRb reportGroup, EReport report) {
		this.reportTypeCode = reportTypeCode;
		this.reportGroup = reportGroup;
		this.report = report;
	}
	
	public String getReportTypeCode() {
		return reportTypeCode;
	}
	
	public EReportGroupRb getReportGroup() {
		return reportGroup;
	}
	
	public EReport getReport() {
		return report;
	}
	
	public static ReportInfo getReportInfo(String reportCode, int reportMenuCode) {
		ReportInfo res = new ReportInfo();
		for (EReportRb eEnum : EReportRb.values()) {
			EReport eReport = eEnum.getReport();
			if (eReport.getCode().equals(reportCode) && eEnum.reportGroup.getMenuCode() == reportMenuCode) {
				res.setId(eEnum.name());
				res.setReport(eReport);
				res.setReportGroup(eEnum.reportGroup.getObject());
				res.setReportTypeCode(eEnum.getReportTypeCode());
				break;
			}
		}
		return res;
	}
}
