#OJKClient
#Mon May 30 21:58:00 ICT 2022
connectionType=internet
proxyUser=
submissionSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\sumber
errorDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\sumber
splitFileSize=500
masterDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\master-data\\hasil
updateOfflineFileDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\resources\\data.dat
submissionDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\selesai
sendindSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\selesai
proxyPassword=
proxyHost=
submissionProcessDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\proses
masterDataSourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\sumber
summarySourceDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\Pelaporan\\sumber
errorDataDoneDir=D\:\\_workspace\\wdg\\ojk\\IKNBClient\\OJK-ASRJS\\error-validasi-server\\hasil
proxyPort=8080
